In [1]:
import pandas as pd
import numpy as np
import os 
os.chdir("D:\\Sales Logistic Project\\Decrypted\\")

df= []
for path, subdirs, files in os.walk("D:\\Sales Logistic Project\\Decrypted\\"):
    for filename in files:
        df_tempa=pd.read_excel(os.path.join(path, filename),index_col=None)
        #print(len(df_tempa))
        df_tempa.iloc[np.where(df_tempa.shape[1]==3)]
        #if len(df_tempa.columns) == 3:
        if 'Packet_Time' in df_tempa.columns:
            #df_tempa['end_dt'] = df_tempa['Period'].map(lambda x:"2021"+"-"+str(x)[17:20]+"-"+str(x)[13:16]+" "+str(x)[20:25])
            df_tempa['Trip_Time'] = pd.to_datetime(df_tempa['Packet_Time'])
            df_tempa['Path'] = str(path)
            df_tempa['Trip_id'] = str(filename)
                #df_tempa['Trip_Id'] = filename                                  
            df.append(df_tempa)
            dfframe = pd.concat(df, axis=0, ignore_index=True)

In [2]:
meta = pd.read_excel('D:\\Sales Logistic Project\\Metadata_v1.xltm',sheet_name='Sheet1')

In [3]:
meta

,SNO,TripIndex,"File Description ( Path, Filename, Shape )",File,Row Count,Col Count,File Format,col1,col2,col3,...,Val1,Val2,Val3,Val4,Val5,Val6,Val7,Val8,Val9,Val10
0,1,1,'D:\\Sales Logistic Project\\Decrypted\\25.10....,'GJ12BV2880_16.10.2021.xls',1450,2,F18,"Lat,Lngt",Period,0,...,"13.003621,79.990784",16/10 10:10 : 16/10 10:15,0,0,0,0,0,0,0,0.0
1,7,1,'D:\\Sales Logistic Project\\Decrypted\\25.10....,'GJ12BV6093_02.09.2021.xls',1891,2,F18,"Lat,Lngt",Period,0,...,"13.004339,79.990413",01/09 10:10 : 01/09 10:15,0,0,0,0,0,0,0,0.0
2,13,1,'D:\\Sales Logistic Project\\Decrypted\\25.10....,'GJ12BV6093_02.10.2021.xls',2019,2,F18,"Lat,Lngt",Period,0,...,"13.004329,79.990362",01/10 10:10 : 01/10 10:15,0,0,0,0,0,0,0,0.0
3,19,1,'D:\\Sales Logistic Project\\Decrypted\\25.10....,'GJ12BV7704_04.10.2021.xls',1162,2,F18,"Lat,Lngt",Period,0,...,"13.004265,79.99063",04/10 10:10 : 04/10 10:15,0,0,0,0,0,0,0,0.0
4,25,1,'D:\\Sales Logistic Project\\Decrypted\\25.10....,'GJ12BV9360_01.10.2021.xls',1163,2,F18,"Lat,Lngt",Period,0,...,"12.995574,79.988806",01/10 10:10 : 01/10 10:15,0,0,0,0,0,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1550,9301,1,'D:\\Sales Logistic Project\\Decrypted\\29.10....,'NL01AC2463_11.09.2021.xlsx',839,3,F10,Latitude,Longitude,Packet Time,...,12.9861,80.0084,44450,0,0,0,0,0,0,0.0
1551,9307,1,'D:\\Sales Logistic Project\\Decrypted\\29.10....,'NL01AC2465_08.09.2021.xlsx',1134,3,F10,Latitude,Longitude,Packet Time,...,12.9862,80.0075,44447,0,0,0,0,0,0,0.0
1552,9313,1,'D:\\Sales Logistic Project\\Decrypted\\29.10....,'NL01AC2465_15.10.2021.xlsx',843,3,F10,Latitude,Longitude,Packet Time,...,12.9861,80.0077,44484,0,0,0,0,0,0,0.0
1553,9319,1,'D:\\Sales Logistic Project\\Decrypted\\29.10....,'NL01AC2469_15.09.2021.xlsx',566,3,F10,Latitude,Longitude,Packet Time,...,12.9864,80.0076,44454,0,0,0,0,0,0,0.0
1554,9325,1,'D:\\Sales Logistic Project\\Decrypted\\29.10....,'NL01AC2469_17.09.2021.xlsx',2269,3,F10,Latitude,Longitude,Packet Time,...,12.9862,80.008,44456,0,0,0,0,0,0,0.0

In [4]:
zip(meta['File'],meta['File Format'])

In [5]:
Meta_dict = dict(zip(meta['File'],meta['File Format']))

In [6]:
Meta_dict

{"'GJ12BV2880_16.10.2021.xls'": 'F18',
 "'GJ12BV6093_02.09.2021.xls'": 'F18',
 "'GJ12BV6093_02.10.2021.xls'": 'F18',
 "'GJ12BV7704_04.10.2021.xls'": 'F18',
 "'GJ12BV9360_01.10.2021.xls'": 'F18',
 "'GJ12BV9630_17.10.2021.xls'": 'F18',
 "'GJ12BV9630_24.09.2021.xls'": 'F18',
 "'HR38Y0900_08.09.2021.xls'": 'F18',
 "'HR38Y0900_13.10.2021.xls'": 'F18',
 "'HR38Y3699_08.09.2021.xls'": 'F18',
 "'HR38Y3699_29.09.2021.xls'": 'F18',
 "'HR38Y9090_04.10.2021.xls'": 'F18',
 "'HR38Y9900_15.09.2021.xls'": 'F18',
 "'HR38Y9909_03.09.2021.xls'": 'F18',
 "'HR55U0990_16.09.2021.xls'": 'F18',
 "'HR55U4599_08.09.2021.xls'": 'F19',
 "'HR55U9009_02.09.2021.xls'": 'F18',
 "'HR69B0063_14.09.2021.xls'": 'F18',
 "'HR69B0333_06.10.2021.xls'": 'F18',
 "'HR69B5571_04.09.2021.xls'": 'F18',
 "'HR69B5643_02.09.2021.xls'": 'F18',
 "'HR69B6777_15.09.2021.xls'": 'F19',
 "'HR69C0144_04.09.2021.xls'": 'F18',
 "'HR69C0900_05.10.2021.xls'": 'F18',
 "'HR69C0990_01.09.2021.xls'": 'F19',
 "'HR69C0990_29.10.2021.xls'": 'F18',
 "'HR69C0999_21.10.2021.xls'": 'F18',
 "'HR69C1134_02.09.2021.xls'": 'F18',
 "'HR69C1134_04.09.2021.xls'": 'F18',
 "'HR69C1233_29.09.2021.xls'": 'F18',
 "'HR69C3006_29.09.2021.xls'": 'F18',
 "'HR69C4599_06.10.2021.xls'": 'F18',
 "'HR69C9009_04.09.2021.xls'": 'F18',
 "'HR69C9099_14.09.2021.xls'": 'F19',
 "'HR63C0484_28.09.2021.xls'": 'F18',
 "'HR63C1907_14.09.2021.xls'": 'F18',
 "'HR63C2126_09.09.2021.xls'": 'F18',
 "'HR63C8486_21.09.2021.xls'": 'F18',
 "'NL01AA1194_27.09.2021.xls'": 'F18',
 "'NL01AB0182_23.09.2021.xls'": 'F18',
 "'NL01AC5558_06.09.2021.xls'": 'F18',
 "'NL01AD1962_23.09.2021.xls'": 'F18',
 "'NL01AE0113_23.09.2021.xls'": 'F18',
 "'NL01AE0115_29.09.2021.xls'": 'F18',
 "'NL01AE0119_07.09.2021.xls'": 'F18',
 "'NL01Q4011_30.09.2021.xls'": 'F18',
 "'NL01Q4161_19.09.2021.xls'": 'F18',
 "'HR38W0101_06.10.2021.xlsx'": 'F10',
 "'HR38W0101_30.09.2021.xlsx'": 'F10',
 "'HR38W0818_03.09.2021.xlsx'": 'F10',
 "'HR38W0818_07.09.2021.xlsx'": 'F10',
 "'HR38W0818_28.09.2021.xlsx'": 'F10',
 "'HR38W0906_25.08.2021.xlsx'": 'F10',
 "'HR38W1140_16.10.2021.xlsx'": 'F10',
 "'HR38W1702_05.09.2021.xlsx'": 'F10',
 "'HR38W1702_16.10.2021.xlsx'": 'F10',
 "'HR38W1702_21.08.2021.xlsx'": 'F10',
 "'HR38W1702_26.08.2021.xlsx'": 'F10',
 "'HR38W1771_21.08.2021.xlsx'": 'F10',
 "'HR38W1771_29.06.2021.xlsx'": 'F10',
 "'HR38W2080_21.08.2021.xlsx'": 'F10',
 "'HR38W2330_12.10.2021.xlsx'": 'F10',
 "'HR38W2501_06.10.2021.xlsx'": 'F10',
 "'HR38W2501_24.09.2021.xlsx'": 'F10',
 "'HR38W3252_04.09.2021.xlsx'": 'F10',
 "'HR38W3252_15.10.2021.xlsx'": 'F10',
 "'HR38W3252_25.08.2021.xlsx'": 'F10',
 "'HR38W3259_01.09.2021.xlsx'": 'F10',
 "'HR38W3259_19.10.2021.xlsx'": 'F10',
 "'HR38W3391_08.10.2021.xlsx'": 'F10',
 "'HR38W3946_23.08.2021.xlsx'": 'F10',
 "'HR38W4158_27.08.2021.xlsx'": 'F10',
 "'HR38W4182_09.09.2021.xlsx'": 'F10',
 "'HR38W4182_27.09.2021.xlsx'": 'F10',
 "'HR38W4395_20.08.2021.xlsx'": 'F11',
 "'HR38W4395_30.08.2021.xlsx'": 'F10',
 "'HR38W4476_07.09.2021.xlsx'": 'F10',
 "'HR38W4476_22.09.2021.xlsx'": 'F10',
 "'HR38W4479_30.08.2021.xlsx'": 'F10',
 "'HR38W4898_20.10.2021.xlsx'": 'F10',
 "'HR38W4900_18.10.2021.xlsx'": 'F10',
 "'HR38W5007_16.10.2021.xlsx'": 'F10',
 "'HR38W5513_05.10.2021.xlsx'": 'F10',
 "'HR38W5513_24.09.2021.xlsx'": 'F10',
 "'HR38W6125_03.09.2021.xlsx'": 'F10',
 "'HR38W6125_15.09.2021.xlsx'": 'F10',
 "'HR38W6289_17.09.2021.xlsx'": 'F10',
 "'HR38W6292_02.09.2021.xlsx'": 'F10',
 "'HR38W6334_13.10.2021.xlsx'": 'F10',
 "'HR38W6438_01.09.2021.xlsx'": 'F10',
 "'HR38W7293_02.09.2021.xlsx'": 'F10',
 "'HR38W7315_15.10.2021.xlsx'": 'F10',
 "'HR38W7820_08.10.2021.xlsx'": 'F10',
 "'HR38W7820_16.10.2021.xlsx'": 'F10',
 "'HR38W8378_16.09.2021.xlsx'": 'F10',
 "'HR38W8378_28.08.2021.xlsx'": 'F10',
 "'HR38W8431_04.10.2021.xlsx'": 'F10',
 "'HR38W8431_22.08.2021.xlsx'": 'F10',
 "'HR38W8521_04.10.2021.xlsx'": 'F10',
 "'HR38W8977_07.09.2021.xlsx'": 'F10',
 "'HR38W9910_28.09.2021.xlsx'": 'F10',
 "'HR38Y0264_30.08.2021.xlsx'": 'F10',
 "'HR38Y7720_07.10.2021.xlsx'": 'F10',
 "'HR38Y8412_21.08.2021.xlsx'": 'F10',
 "'HR38Y9302_20.08.2021.xlsx'": 'F10',
 "'HR38Y9761_26.08.2021.xlsx'": 'F10',
 "'HR63C0978_04.09.2021.xlsx'": 'F10',
 "'HR63C0978_05.10.2021.xlsx'": 'F10',
 "'HR63C0978_20.09.2021.xlsx'": 'F10',
 "'HR63C1683_23.08.2021.xlsx'": 'F10',
 "'HR63C1683_31.08.2021.xlsx'": 'F10',
 "'HR63C1690_24.09.2021.xlsx'": 'F10',
 "'HR63C1768_15.09.2021.xlsx'": 'F10',
 "'HR63C1768_27.08.2021.xlsx'": 'F10',
 "'HR63C1768_30.09.2021.xlsx'": 'F10',
 "'HR63C2234_11.10.2021.xlsx'": 'F10',
 "'HR63C3257_15.09.2021.xlsx'": 'F10',
 "'HR63C3381_14.09.2021.xlsx'": 'F10',
 "'HR63C3381_27.08.2021.xlsx'": 'F10',
 "'HR63C3688_26.08.2021.xlsx'": 'F10',
 "'HR63C3817_25.08.2021.xlsx'": 'F10',
 "'HR63C3817_30.09.2021.xlsx'": 'F10',
 "'HR63C3828_01.09.2021.xlsx'": 'F10',
 "'HR63C3828_24.08.2021.xlsx'": 'F10',
 "'HR63C4207_04.09.2021.xlsx'": 'F10',
 "'HR63C4207_25.09.2021.xlsx'": 'F10',
 "'HR63C4226_04.09.2021.xlsx'": 'F10',
 "'HR63C4226_23.09.2021.xlsx'": 'F10',
 "'HR63C5602_14.09.2021.xlsx'": 'F10',
 "'HR63C5602_28.08.2021.xlsx'": 'F10',
 "'HR63C6085_21.08.2021.xlsx'": 'F10',
 "'HR63C6534_01.09.2021.xlsx'": 'F10',
 "'HR63C6534_05.10.2021.xlsx'": 'F10',
 "'HR63C6534_14.09.2021.xlsx'": 'F10',
 "'HR63C7352_09.09.2021.xlsx'": 'F10',
 "'HR63C7352_29.09.2021.xlsx'": 'F10',
 "'HR63C7497_06.09.2021.xlsx'": 'F10',
 "'HR63C7497_14.09.2021.xlsx'": 'F10',
 "'HR63C7550_15.10.2021.xlsx'": 'F10',
 "'HR63C7637_21.09.2021.xlsx'": 'F10',
 "'HR63C8051_24.08.2021.xlsx'": 'F10',
 "'HR63C8307_07.09.2021.xlsx'": 'F10',
 "'HR63C8307_25.08.2021.xlsx'": 'F10',
 "'HR63C8463_05.10.2021.xlsx'": 'F10',
 "'HR63C8463_21.08.2021.xlsx'": 'F10',
 "'HR63C8695_04.10.2021.xlsx'": 'F10',
 "'HR63C8695_18.09.2021.xlsx'": 'F10',
 "'HR63C8833_04.10.2021.xlsx'": 'F10',
 "'HR63C8833_15.09.2021.xlsx'": 'F10',
 "'HR63C8992_07.09.2021.xlsx'": 'F10',
 "'HR63C8992_14.09.2021.xlsx'": 'F10',
 "'HR63C9101_01.10.2021.xlsx'": 'F10',
 "'HR63C9101_14.09.2021.xlsx'": 'F10',
 "'HR63C9101_16.10.2021.xlsx'": 'F10',
 "'HR63C9101_30.08.2021.xlsx'": 'F10',
 "'HR63C9161_21.09.2021.xlsx'": 'F10',
 "'HR63C9192_03.09.2021.xlsx'": 'F10',
 "'HR63C9192_25.08.2021.xlsx'": 'F10',
 "'HR63C9429_04.09.2021.xlsx'": 'F10',
 "'HR63C9429_14.09.2021.xlsx'": 'F10',
 "'HR63C9429_22.09.2021.xlsx'": 'F10',
 "'KA01AH1692_25.09.2021.xlsx'": 'F10',
 "'KA01AH1693_16.09.2021.xlsx'": 'F10',
 "'NL010087_08.09.2021.xlsx'": 'F10',
 "'NL010320_16.09.2021.xlsx'": 'F10',
 "'NL01AA0975_31.08.2021.xlsx'": 'F10',
 "'NL01AA0976_03.09.2021.xlsx'": 'F10',
 "'NL01AA0977_02.09.2021.xlsx'": 'F10',
 "'NL01AA0977_24.08.2021.xlsx'": 'F10',
 "'NL01AA0979_23.08.2021.xlsx'": 'F10',
 "'NL01AA0980_31.08.2021.xlsx'": 'F10',
 "'NL01AA3072_03.09.2021.xlsx'": 'F10',
 "'NL01AA3073_21.08.2021.xlsx'": 'F10',
 "'NL01AA9622_07.08.2021.xlsx'": 'F10',
 "'NL01AA9623_03.08.2021.xlsx'": 'F10',
 "'NL01AA9627_13.10.2021.xlsx'": 'F10',
 "'NL01AA9627_18.08.2021.xlsx'": 'F10',
 "'NL01AA9629_07.09.2021.xlsx'": 'F10',
 "'NL01Q-9682_08.08.2021.xlsx'": 'F10',
 "'NL01Q3547_06.08.2021.xlsx'": 'F10',
 "'NL01Q3548_08.08.2021.xlsx'": 'F10',
 "'NL01Q3548_27.09.2021.xlsx'": 'F10',
 "'NL01Q3550_30.09.2021.xlsx'": 'F10',
 "'NL01Q3735_03.08.2021.xlsx'": 'F10',
 "'NL01Q3735_17.09.2021.xlsx'": 'F10',
 "'NL01Q9684_15.09.2021.xlsx'": 'F10',
 "'NL01Q9685_04.09.2021.xlsx'": 'F10',
 "'NL01Q9685_24.08.2021.xlsx'": 'F10',
 "'NL01Q9687_12.08.2021.xlsx'": 'F10',
 "'HR38X7641_29.09.2021.xlsx'": 'F10',
 "'HR47B5739_24.09.2021.xlsx'": 'F10',
 "'HR47B5848_16.09.2021.xlsx'": 'F10',
 "'HR47B5848_29.09.2021.xlsx'": 'F10',
 "'HR47B5857_23.09.2021.xlsx'": 'F10',
 "'HR47B5858_28.09.2021.xlsx'": 'F10',
 "'HR47B5862_05.10.2021.xlsx'": 'F10',
 "'HR47B5862_20.10.2021.xlsx'": 'F10',
 "'HR47B5919_15.09.2021.xlsx'": 'F10',
 "'HR47B8204_04.10.2021.xlsx'": 'F10',
 "'HR47B8205_08.10.2021.xlsx'": 'F10',
 "'HR47B8205_18.09.2021.xlsx'": 'F10',
 "'HR47B8206_18.10.2021.xlsx'": 'F10',
 "'HR47B8207_04.10.2021.xlsx'": 'F10',
 "'HR47B8207_15.09.2021.xlsx'": 'F10',
 "'HR47B8210_12.10.2021.xlsx'": 'F10',
 "'HR47B8210_28.09.2021.xlsx'": 'F10',
 "'HR47C2315_05.10.2021.xlsx'": 'F10',
 "'HR47C2457_14.10.2021.xlsx'": 'F10',
 "'HR47C2466_27.09.2021.xlsx'": 'F10',
 "'HR47C2516_04.10.2021.xlsx'": 'F10',
 "'HR47C9485_02.10.2021.xlsx'": 'F10',
 "'HR47D0169_12.10.2021.xlsx'": 'F10',
 "'HR47D1108_08.10.2021.xlsx'": 'F10',
 "'HR47D3335_17.10.2021.xlsx'": 'F10',
 "'HR47D4329_16.09.2021.xlsx'": 'F10',
 "'HR47D4506_30.09.2021.xlsx'": 'F10',
 "'HR47D5328_15.10.2021.xlsx'": 'F10',
 "'HR47D5806_23.09.2021.xlsx'": 'F10',
 "'HR47D7273_16.10.2021.xlsx'": 'F10',
 "'HR47D9032_28.09.2021.xlsx'": 'F10',
 "'HR47D9499_04.10.2021.xlsx'": 'F10',
 "'NL01N4838_19.09.2021.xlsx'": 'F10',
 "'NL01N4840_30.09.2021.xlsx'": 'F10',
 "'NL01N4841_06.10.2021.xlsx'": 'F10',
 "'NL01N5450_30.09.2021.xlsx'": 'F10',
 "'NL01N5453_23.09.2021.xlsx'": 'F10',
 "'NL01N5459_30.09.2021.xlsx'": 'F10',
 "'NL01N7422_23.09.2021.xlsx'": 'F10',
 "'NL01N7423_02.10.2021.xlsx'": 'F10',
 "'GJ06AZ6068_07.09.2021.xls'": 'F18',
 "'GJ06AZ6243_02.09.2021.xls'": 'F18',
 "'GJ06AZ6260_13.09.2021.xls'": 'F18',
 "'GJ12BX8238_06.10.2021.xls'": 'F18',
 "'GJ12BX8569_15.09.2021.xls'": 'F18',
 "'GJ12BX8657_21.09.2021.xls'": 'F18',
 "'GJ12BY0447_09.09.2021.xls'": 'F18',
 "'GJ12BY0482_21.09.2021.xls'": 'F18',
 "'HR55AG1126_17.10.2021.xlsx'": 'F10',
 "'HR55P6866_15.10.2021.xlsx'": 'F10',
 "'HR55P9987_30.09.2021.xlsx'": 'F10',
 "'HR55U7776_04.10.2021.xlsx'": 'F10',
 "'NL01AC0125_18.09.2021.xlsx'": 'F10',
 "'NL01N1253_16.10.2021.xlsx'": 'F10',
 "'NL01N1714_23.09.2021.xlsx'": 'F10',
 "'NL01AA1635_14.09.2021.xlsx'": 'F10',
 "'NL01AB5298_13.08.2021.xlsx'": 'F10',
 "'NL01AB5300_12.08.2021.xlsx'": 'F10',
 "'NL01AC3023_05.08.2021.xlsx'": 'F10',
 "'NL01AD0008_12.08.2021.xlsx'": 'F10',
 "'NL01N6544_03.08.2021.xlsx'": 'F10',
 "'NL01N6544_07.08.2021.xlsx'": 'F10',
 "'NL01N7489_23.08.2021.xlsx'": 'F10',
 "'PB65AD8137_11.08.2021.xlsx'": 'F10',
 "'PB65AD8139_26.08.2021.xlsx'": 'F10',
 "'UP82T4576_24.08.2021.xlsx'": 'F10',
 "'UP82T4684_26.08.2021.xlsx'": 'F10',
 "'UP82T4685_19.08.2021.xlsx'": 'F10',
 "'UP82T4739_03.08.2021.xlsx'": 'F10',
 "'UP82T4740_11.08.2021.xlsx'": 'F10',
 "'UP82T4740_31.08.2021.xlsx'": 'F10',
 "'UP82T4741_01.08.2021.xlsx'": 'F10',
 "'UP82T4744_09.08.2021.xlsx'": 'F10',
 "'UP82T5508_04.08.2021.xlsx'": 'F10',
 "'UP82T5509_17.08.2021.xlsx'": 'F10',
 "'UP82T5513_17.08.2021.xlsx'": 'F10',
 "'UP82T5513_19.08.2021.xlsx'": 'F10',
 "'UP82T5514_14.09.2021.xlsx'": 'F10',
 "'UP82T6226_28.08.2021.xlsx'": 'F10',
 "'UP82T6227_04.09.2021.xlsx'": 'F10',
 "'UP82T6227_23.08.2021.xlsx'": 'F10',
 "'UP82T6229_10.08.2021.xlsx'": 'F10',
 "'HR55AD4862_08.09.2021.xls'": 'F18',
 "'HR55AD4960_08.09.2021.xls'": 'F18',
 "'HR55AD6041_14.09.2021.xls'": 'F18',
 "'HR55AD6674_11.09.2021.xls'": 'F18',
 "'HR55AE0996_01.09.2021.xls'": 'F8',
 "'HR55AE5398_03.09.2021.xls'": 'F18',
 "'HR55AE6377_08.09.2021.xls'": 'F18',
 "'HR55AE9866_11.09.2021.xls'": 'F18',
 "'HR55AE9932_11.09.2021.xls'": 'F18',
 "'HR55AE9932_17.09.2021.xls'": 'F18',
 "'HR55AH2334_09.09.2021.xls'": 'F18',
 "'HR55N4735_04.09.2021.xls'": 'F18',
 "'HR55N4735_08.09.2021.xls'": 'F18',
 "'HR55P2125_13.09.2021.xls'": 'F18',
 "'HR55Q3611_17.09.2021.xls'": 'F18',
 "'HR55Q3620_16.09.2021.xls'": 'F18',
 "'HR55Q4059_02.09.2021.xls'": 'F18',
 "'HR55Q4060_02.09.2021.xls'": 'F18',
 "'HR55Q4063_24.09.2021.xls'": 'F18',
 "'HR55Q4064_16.09.2021.xls'": 'F18',
 "'HR55Q4068_19.09.2021.xls'": 'F18',
 "'HR55Q6064_04.09.2021.xls'": 'F18',
 "'HR55Q7840_16.09.2021.xls'": 'F18',
 "'HR55Q8507_26.09.2021.xls'": 'F18',
 "'HR55R3436_09.09.2021.xls'": 'F18',
 "'HR55R3509_01.09.2021.xls'": 'F18',
 "'HR55R3509_15.09.2021.xls'": 'F18',
 "'HR55R3509_30.09.2021.xls'": 'F18',
 "'HR55R5799_04.09.2021.xls'": 'F18',
 "'HR55R5801_04.09.2021.xls'": 'F18',
 "'HR55R5801_16.09.2021.xls'": 'F18',
 "'HR55R7135_02.09.2021.xls'": 'F18',
 "'HR55R7135_11.09.2021.xls'": 'F19',
 "'NL01AA8908_01.09.2021.xls'": 'F18',
 "'NL01AB5274_03.09.2021.xls'": 'F18',
 "'NL01AE8917_25.09.2021.xls'": 'F18',
 "'NL01AF0166_22.09.2021.xls'": 'F18',
 "'NL01Q0461_04.09.2021.xls'": 'F18',
 "'NL01Q0462_17.09.2021.xls'": 'F8',
 "'NL01Q0462_29.09.2021.xls'": 'F8',
 "'NL01Q0463_01.09.2021.xls'": 'F8',
 "'NL01Q1243_13.09.2021.xls'": 'F18',
 "'NL01Q7638_25.09.2021.xls'": 'F18',
 "'NL01Q7639_08.09.2021.xls'": 'F18',
 "'UP32KN7118_04.09.2021.xls'": 'F19',
 "'UP32KN7118_28.09.2021.xls'": 'F18',
 "'HR55AF1302_01.09.2021.xlsx'": 'F10',
 "'HR55AF8436_17.09.2021.xlsx'": 'F10',
 "'HR55AG0695_22.09.2021.xlsx'": 'F10',
 "'HR55AG1650_30.09.2021.xlsx'": 'F10',
 "'HR55AG2034_02.09.2021.xlsx'": 'F10',
 "'HR55AG2403_12.10.2021.xlsx'": 'F10',
 "'HR55AG2612_19.10.2021.xlsx'": 'F10',
 "'HR55AG2968_08.10.2021.xlsx'": 'F10',
 "'HR55AG2968_10.09.2021.xlsx'": 'F10',
 "'HR55AG4310_01.09.2021.xlsx'": 'F10',
 "'HR55AG4871_18.09.2021.xlsx'": 'F10',
 "'HR55AG5550_02.09.2021.xlsx'": 'F10',
 "'HR55AG5703_28.09.2021.xlsx'": 'F10',
 "'HR55AG6163_16.09.2021.xlsx'": 'F10',
 "'HR55AG7820_28.09.2021.xlsx'": 'F10',
 "'HR55AG8652_02.09.2021.xlsx'": 'F10',
 "'HR55AH2802_07.10.2021.xlsx'": 'F10',
 "'HR55AH9749_01.09.2021.xlsx'": 'F10',
 "'HR55AH9749_27.09.2021.xlsx'": 'F10',
 "'HR55AJ9963_24.09.2021.xlsx'": 'F10',
 "'HR55P6863_04.09.2021.xlsx'": 'F10',
 "'HR55P6870_08.10.2021.xlsx'": 'F10',
 "'HR55Q0459_15.09.2021.xlsx'": 'F10',
 "'HR55Q0463_04.09.2021.xlsx'": 'F10',
 "'HR55R0765_24.09.2021.xlsx'": 'F10',
 "'HR55R0769_25.09.2021.xlsx'": 'F10',
 "'NL01AA0061_07.09.2021.xlsx'": 'F10',
 "'NL01AA0072_03.09.2021.xlsx'": 'F10',
 "'NL01AA0462_02.09.2021.xlsx'": 'F10',
 "'NL01AA0473_07.09.2021.xlsx'": 'F10',
 "'NL01AA0508_16.10.2021.xlsx'": 'F10',
 "'NL01AA3778 _02.09.2021.xlsx'": 'F10',
 "'NL01AA6208_04.10.2021.xlsx'": 'F10',
 "'NL01AA6217_05.10.2021.xlsx'": 'F10',
 "'NL01AA6836_01.09.2021.xlsx'": 'F10',
 "'NL01AC0123_20.10.2021.xlsx'": 'F10',
 "'NL01AC1238_26.09.2021.xlsx'": 'F10',
 "'NL01AC1411_06.09.2021.xlsx'": 'F10',
 "'NL01AC1415_17.09.2021.xlsx'": 'F10',
 "'NL01AC1420_02.09.2021.xlsx'": 'F10',
 "'NL01AD7750_08.09.2021.xlsx'": 'F10',
 "'NL01K8833_14.09.2021.xlsx'": 'F10',
 "'NL01N1267_08.09.2021.xlsx'": 'F10',
 "'NL01N1286_28.09.2021.xlsx'": 'F10',
 "'NL01Q1455_22.09.2021.xlsx'": 'F10',
 "'NL01Q4059_01.09.2021.xlsx'": 'F10',
 "'NL01Q7122_14.09.2021.xlsx'": 'F10',
 "'NL01Q7126_23.09.2021.xlsx'": 'F10',
 "'NL01Q9566_02.09.2021.xlsx'": 'F10',
 "'PB11AU7644_01.09.2021.xlsx'": 'F10',
 "'HR55P9886_02.09.2021.xls'": 'F18',
 "'HR55Q9463_04.09.2021.xls'": 'F18',
 "'HR55R6352_30.09.2021.xls'": 'F18',
 "'HR55R8025_14.09.2021.xls'": 'F18',
 "'NL01AA6010_23.09.2021.xls'": 'F18',
 "'NL01N2642_25.09.2021.xls'": 'F18',
 "'NL01N6132_18.09.2021.xls'": 'F18',
 "'NL01N6139_18.09.2021.xls'": 'F18',
 "'NL01N8578_21.09.2021.xls'": 'F18',
 "'NL01N8784_06.09.2021.xls'": 'F18',
 "'NL01Q4127_17.09.2021.xls'": 'F18',
 "'NL01Q4133_05.09.2021.xls'": 'F18',
 "'NL01Q4297_30.09.2021.xls'": 'F18',
 "'NL01Q4299_30.09.2021.xls'": 'F18',
 "'PB11BR1776_17.09.2021.xls'": 'F18',
 "'PB65AD8136_02.09.2021.xls'": 'F18',
 "'PB65AD8149_14.09.2021.xls'": 'F18',
 "'PB65AD8157_06.09.2021.xls'": 'F18',
 "'NL01N6312_09.09.21.xlsx'": 'F10',
 "'NL01N9764_08.09.21.xlsx'": 'F10',
 "'NL01Q4110_11.09.21.xlsx'": 'F10',
 "'NL01Q4111_30.09.21.xlsx'": 'F10',
 "'NL01Q4993_09.09.21.xlsx'": 'F10',
 "'NL01Q4993_18.09.21.xlsx'": 'F10',
 "'NL01Q7950_03.09.21.xlsx'": 'F10',
 "'NL01Q7953_25.09.21.xlsx'": 'F10',
 "'NL01Q9159_04.09.21.xlsx'": 'F10',
 "'NL01AB3573_03.09.2021.xls'": 'F18',
 "'NL01AE2295_09.09.2021.xls'": 'F18',
 "'NL01AE2295_18.09.2021.xls'": 'F18',
 "'NL01AE2340_02.09.2021.xls'": 'F18',
 "'NL01AE2592_02.09.2021.xls'": 'F18',
 "'NL01AE4356_14.08.2021.xls'": 'F18',
 "'NL01AE4374_02.09.2021.xls'": 'F18',
 "'NL01AE4410_19.08.2021.xls'": 'F18',
 "'NL01AE4419_21.08.2021.xls'": 'F18',
 "'NL01AE4599_02.09.2021.xls'": 'F18',
 "'NL01AE4601_28.08.2021.xls'": 'F18',
 "'NL01AE4601_28.09.2021.xls'": 'F18',
 "'NL01AE4617_17.09.2021.xls'": 'F18',
 "'NL01AE4618_19.08.2021.xls'": 'F18',
 "'NL01AE4618_24.09.2021.xls'": 'F18',
 "'NL01AE4628_12.08.2021.xls'": 'F18',
 "'NL01AE4634_11.08.2021.xls'": 'F18',
 "'NL01AE4634_14.08.2021.xls'": 'F18',
 "'NL01AE4641_03.08.2021.xls'": 'F18',
 "'NL01AE4642_12.08.2021.xls'": 'F18',
 "'NL01AE4646_03.09.2021.xls'": 'F18',
 "'NL01AE4655_19.08.2021.xls'": 'F18',
 "'NL01AE4670_14.08.2021.xls'": 'F18',
 "'NL01AE4690_21.08.2021.xls'": 'F18',
 "'NL01AE4691_21.08.2021.xls'": 'F18',
 "'NL01AE4691_27.09.2021.xls'": 'F18',
 "'NL01AE4694_26.08.2021.xls'": 'F18',
 "'NL01AE4698_03.09.2021.xls'": 'F18',
 "'NL01AE4698_09.09.2021.xls'": 'F18',
 "'NL01AE4743_07.08.2021.xls'": 'F18',
 "'NL01L6300_19.08.2021.xls'": 'F18',
 "'NL01L6444_17.08.2021.xls'": 'F18',
 "'NL02N5292_26.08.2021.xls'": 'F18',
 "'NL02N5490_27.08.2021.xls'": 'F18',
 "'NL02N5661_03.08.2021.xls'": 'F18',
 "'NL02N5661_18.08.2021.xls'": 'F18',
 "'NL02Q3501_26.08.2021.xls'": 'F18',
 "'NL02Q3537_21.09.2021.xls'": 'F18',
 "'NL02Q3564_20.08.2021.xls'": 'F18',
 "'NL02Q3654_18.09.2021.xls'": 'F18',
 "'NL02Q3672_20.08.2021.xls'": 'F18',
 "'NL02Q3681_11.08.2021.xls'": 'F18',
 "'NL02Q3708_12.08.2021.xls'": 'F18',
 "'NL02Q3726_29.09.2021.xls'": 'F18',
 "'NL02Q3753_16.09.2021.xls'": 'F18',
 "'NL02Q3753_21.09.2021.xls'": 'F18',
 "'NL02Q3924_14.08.2021.xls'": 'F18',
 "'NL02Q6336_03.08.2021.xls'": 'F18',
 "'NL02Q6336_29.09.2021.xls'": 'F18',
 "'HR69C7777_30.09.2021.xlsx'": 'F10',
 "'NL01AA3956_02.09.2021.xlsx'": 'F10',
 "'NL01AA4737_04.09.2021.xlsx'": 'F10',
 "'NL01AA4737_25.09.2021.xlsx'": 'F10',
 "'NL01AA4740_04.09.2021.xlsx'": 'F10',
 "'NL01AA9456_11.09.2021.xlsx'": 'F10',
 "'NL01AA9458_24.09.2021.xlsx'": 'F10',
 "'NL01AA9778_24.09.2021.xlsx'": 'F10',
 "'NL01AB0179_18.09.2021.xlsx'": 'F10',
 "'NL01AB0561_21.09.2021.xlsx'": 'F10',
 "'NL01AB8774_09.09.2021.xlsx'": 'F10',
 "'NL01AB9407_29.09.2021.xlsx'": 'F10',
 "'NL01AB9977_16.09.2021.xlsx'": 'F10',
 "'NL01AB9978_02.09.2021.xlsx'": 'F10',
 "'NL01AB9980_12.09.2021.xlsx'": 'F10',
 "'NL01AB9980_16.09.2021.xlsx'": 'F10',
 "'NL01AE4203_02.09.2021.xlsx'": 'F10',
 "'NL01AE9795_08.09.2021.xlsx'": 'F10',
 "'NL01AE9800_01.09.2021.xlsx'": 'F10',
 "'NL01AE9803_22.09.2021.xlsx'": 'F10',
 "'NL01L5417_28.09.2021.xlsx'": 'F10',
 "'NL01Q5690_24.09.2021.xlsx'": 'F10',
 "'NL01Q5693_24.09.2021.xlsx'": 'F10',
 "'NL01AA4452_01.09.2021.xls'": 'F18',
 "'NL01AA4452_24.08.2021.xls'": 'F18',
 "'NL01AA4455_05.10.2021.xls'": 'F18',
 "'NL01AA4461_19.10.2021.xls'": 'F18',
 "'NL01AA4462_22.08.2021.xls'": 'F18',
 "'NL01AA4465_27.08.2021.xls'": 'F18',
 "'NL01AA4468_23.09.2021.xls'": 'F18',
 "'NL01AA5761_04.09.2021.xls'": 'F18',
 "'NL01AA5761_04.10.2021.xls'": 'F18',
 "'NL01AA5761_21.09.2021.xls'": 'F18',
 "'NL01AA5761_25.08.2021.xls'": 'F18',
 "'NL01AA5764_26.08.2021.xls'": 'F18',
 "'NL01AA5766_30.09.2021.xls'": 'F18',
 "'NL01AA5851_25.08.2021.xls'": 'F18',
 "'NL01AA5862_16.10.2021.xls'": 'F18',
 "'NL01AA6296_08.09.2021.xls'": 'F18',
 "'NL01AB0411_16.10.2021.xls'": 'F18',
 "'NL01AB0677_30.09.2021.xls'": 'F18',
 "'NL01AB0681_04.10.2021.xls'": 'F18',
 "'NL01AB0684_04.10.2021.xls'": 'F18',
 "'NL01AB0684_25.08.2021.xls'": 'F18',
 "'NL01N8954_22.08.2021.xls'": 'F18',
 "'NL01N8966_29.09.2021.xls'": 'F18',
 "'NL01Q1055_17.10.2021.xls'": 'F18',
 "'NL01Q1057_22.08.2021.xls'": 'F18',
 "'NL01Q1069_04.10.2021.xls'": 'F18',
 "'NL01Q1069_24.08.2021.xls'": 'F18',
 "'NL01Q1070_19.10.2021.xls'": 'F18',
 "'NL01Q1261_30.09.2021.xls'": 'F18',
 "'NL01Q1270_12.10.2021.xls'": 'F18',
 "'NL01Q1271_24.09.2021.xls'": 'F18',
 "'NL01Q1282_16.10.2021.xls'": 'F18',
 "'NL01Q1282_30.08.2021.xls'": 'F18',
 "'NL01Q1285_18.09.2021.xls'": 'F18',
 "'NL01Q1408_18.09.2021.xls'": 'F18',
 "'NL01Q2034_29.09.2021.xls'": 'F18',
 "'NL01Q2040_25.08.2021.xls'": 'F18',
 "'NL01Q2041_20.10.2021.xls'": 'F18',
 "'NL01Q2045_28.08.2021.xls'": 'F18',
 "'NL01Q8960_27.08.2021.xls'": 'F18',
 "'GJ06AX5749_09.09.2021.xlsx'": 'F10',
 "'GJ06AX5749_13.09.2021.xlsx'": 'F10',
 "'HR55T8262_04.10.2021.xls'": 'F19',
 "'UK04CA9200_23.09.2021.xlsx'": 'F10',
 "'UK04CA9212_20.09.2021.xlsx'": 'F10',
 "'UK04CA9290_14.09.2021.xlsx'": 'F10',
 "'UK04CA9369_03.09.2021.xlsx'": 'F10',
 "'UK04CA9370_08.09.2021.xlsx'": 'F10',

In [7]:
file_frmts = meta.set_index('File').to_dict()['File Format']

In [8]:
#print(x["'NL01AC2907_02.09.2021.xlsx'"])
df_f18=[]
for path, subdirs, files in os.walk("D:\\Sales Logistic Project\\Decrypted\\"):
    for filename in files:
        fmt_typ = file_frmts[("'" + filename + "'")]   
        if (fmt_typ == "F18"):
            df_tempa=pd.read_excel(os.path.join(path, filename),index_col=None)
            df_tempa['Trip_id'] = str(filename)
            df_tempa[['Latitude', 'Longitude']] = df_tempa['Lat,Lngt'].str.split(',', 1, expand=True)
            df_tempa['Latitude'] = df_tempa['Latitude'].astype(float)
            df_tempa['Longitude'] = df_tempa['Longitude'].astype(float)
            df_tempa['GPS_dt_tm'] = df_tempa['Period'].map(lambda x:"2021"+"-"+str(x)[17:20]+"-"+str(x)[13:16]+" "+str(x)[20:25])
            df_tempa.drop('Period', axis=1, inplace=True)
            df_f18.append(df_tempa)
            dfframe_format18 = pd.concat(df_f18, axis=0, ignore_index=True)
            dfframe_format18.Trip_id = dfframe_format18.Trip_id.str.replace('[.xls]', '')
            dfframe_format18.Trip_id = dfframe_format18.Trip_id.str.replace('[.xlsx]', '')
            df_obj = dfframe_format18.select_dtypes(['object'])
            dfframe_format18[df_obj.columns] = df_obj.apply(lambda x: x.str.strip())

In [9]:
dfframe_format18.head(2)

,"Lat,Lngt",Trip_id,Latitude,Longitude,GPS_dt_tm
0,"13.003621,79.990784",GJ12BV2880_16102021,13.003621,79.990784,2021-10 - 16 10:15
1,"13.003621,79.990784",GJ12BV2880_16102021,13.003621,79.990784,2021-10 - 16 10:20

In [14]:
dfframe_format18.shape

(830962, 5)

In [10]:
dfframe_format18.Trip_id.value_counts()

NL01N6139_18092021    2881
NL01N5071_27082021    2881
NL01L7328_01082021    2880
NL01L8612_25082021    2880
NL01L8613_11082021    2879
                      ...
NL01Q4982_22092021      33
GJ14X5039_24092021      31
NL01Q4965_23092021      28
NL01Q3258_23092021      25
NL01Q7267_24092021      17
Name: Trip_id, Length: 672, dtype: int64

In [11]:
dfframe_format18.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 830962 entries, 0 to 830961
Data columns (total 5 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   Lat,Lngt   830310 non-null  object
 1   Trip_id    830962 non-null  object
 2   Latitude   830310 non-null  float64
 3   Longitude  830310 non-null  float64
 4   GPS_dt_tm  830962 non-null  object
dtypes: float64(2), object(3)
memory usage: 31.7+ MB

In [18]:
dfframe_format18.isnull().sum()

Trip_id        0
Lat,Lngt     652
Latitude     652
Longitude    652
GPS_dt_tm      0
dtype: int64

In [13]:
#dfframe_format18.iloc[np.where(dfframe_test_a.isnull())]

In [19]:
dfframe_format18 = dfframe_format18.dropna(how='any',axis=0)

In [24]:
dfframe_format18.Trip_id.value_counts().count()

672

In [25]:
dfframe_format18.isnull().sum()

Trip_id      0
Lat,Lngt     0
Latitude     0
Longitude    0
GPS_dt_tm    0
dtype: int64

In [26]:
dfframe_format18.Trip_id.value_counts().sum()

830310

In [27]:
830962 - 830310

652

In [28]:
dfframe_format18.head(2)

,Trip_id,"Lat,Lngt",Latitude,Longitude,GPS_dt_tm
0,GJ12BV2880_16102021,"13.003621,79.990784",13.003621,79.990784,2021-10 - 16 10:15
1,GJ12BV2880_16102021,"13.003621,79.990784",13.003621,79.990784,2021-10 - 16 10:20

In [29]:
dfframe_format18 = dfframe_format18[['Trip_id','Lat,Lngt','Latitude','Longitude','GPS_dt_tm']]

In [30]:
dfframe_format18

,Trip_id,"Lat,Lngt",Latitude,Longitude,GPS_dt_tm
0,GJ12BV2880_16102021,"13.003621,79.990784",13.003621,79.990784,2021-10 - 16 10:15
1,GJ12BV2880_16102021,"13.003621,79.990784",13.003621,79.990784,2021-10 - 16 10:20
2,GJ12BV2880_16102021,"13.003621,79.990784",13.003621,79.990784,2021-10 - 16 10:25
3,GJ12BV2880_16102021,"13.003621,79.990784",13.003621,79.990784,2021-10 - 16 10:30
4,GJ12BV2880_16102021,"13.003621,79.990784",13.003621,79.990784,2021-10 - 16 10:35
...,...,...,...,...,...
830956,NL01Q9795_02092021,"22.588661,88.221088",22.588661,88.221088,2021-09 - 07 23:35
830957,NL01Q9795_02092021,"22.58866,88.221085",22.588660,88.221085,2021-09 - 07 23:40
830958,NL01Q9795_02092021,"22.588661,88.221088",22.588661,88.221088,2021-09 - 07 23:45
830959,NL01Q9795_02092021,"22.588661,88.221088",22.588661,88.221088,2021-09 - 07 23:55
830960,NL01Q9795_02092021,"22.58866,88.221085",22.588660,88.221085,2021-09 - 07 23:57

In [ ]:
# format 17 
# most records have just the start time

In [52]:
#print(x["'NL01AC2907_02.09.2021.xlsx'"])
df_f17=[]
for path, subdirs, files in os.walk("D:\\Sales Logistic Project\\Decrypted\\"):
    for filename in files:
        fmt_typ = file_frmts[("'" + filename + "'")]   
        if (fmt_typ == "F17"):
            df_tempa=pd.read_excel(os.path.join(path, filename),index_col=None)
            df_tempa['Trip_id'] = str(filename)
            df_tempa['Period'] = df_tempa['Period'].replace(r'\n',' ', regex=True)
            df_tempa['Lat,Lngt'] = df_tempa['Lat,Lngt'].replace(r'\n',' ', regex=True)
            df_tempa['Lat,Lngt'] = df_tempa['Lat,Lngt'].str.replace(' ','')
            df_tempa[['Latitude', 'Longitude']] = df_tempa['Lat,Lngt'].str.split(',', 1, expand=True)
            #df_tempa.drop(df_tempa.loc[df_tempa['Lat,Lngt']=='0.02764413.026074'].index, inplace=True)
            df_tempa['Latitude'] = df_tempa['Latitude'].astype(float)
            df_tempa['Longitude'] = df_tempa['Longitude'].astype(float)
            df_tempa['GPS_dt_tm'] = df_tempa['Period'].map(lambda x:"2021"+"-"+str(x)[3:5]+"-"+str(x)[0:2]+" "+str(x)[6:11])
            df_tempa['GPS_dt_tm'] = pd.to_datetime(df_tempa['GPS_dt_tm'])
            df_tempa.drop('Period', axis=1, inplace=True)
            df_f17.append(df_tempa)
            dfframe_format17 = pd.concat(df_f17, axis=0, ignore_index=True)
            dfframe_format17.Trip_id = dfframe_format17.Trip_id.str.replace('[.xls]', '')
            dfframe_format17.Trip_id = dfframe_format17.Trip_id.str.replace('[.xlsx]', '')
            #dfframe_format17.Trip_id = dfframe_format17.Trip_id.str.replace('[.xltm]', '')
            df_obj = dfframe_format17.select_dtypes(['object'])
            dfframe_format17[df_obj.columns] = df_obj.apply(lambda x: x.str.strip())

In [53]:
#17/10 00:00

In [54]:
dfframe_format17.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6758 entries, 0 to 6757
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Lat,Lngt   6749 non-null   object
 1   Trip_id    6758 non-null   object
 2   Latitude   6749 non-null   float64
 3   Longitude  6749 non-null   float64
 4   GPS_dt_tm  6758 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(2)
memory usage: 264.1+ KB

In [55]:
dfframe_format17

,"Lat,Lngt",Trip_id,Latitude,Longitude,GPS_dt_tm
0,"13.024057,80.027244",NL01AA3593_17102021,13.024057,80.027244,2021-10-17 00:00:00
1,"13.024057,80.027244",NL01AA3593_17102021,13.024057,80.027244,2021-10-17 00:06:00
2,"13.024057,80.027244",NL01AA3593_17102021,13.024057,80.027244,2021-10-17 00:12:00
3,"13.024057,80.027244",NL01AA3593_17102021,13.024057,80.027244,2021-10-17 00:18:00
4,"13.024057,80.027244",NL01AA3593_17102021,13.024057,80.027244,2021-10-17 00:24:00
...,...,...,...,...,...
6753,"21.134447,72.755644",NL01Q3114_04102021,21.134447,72.755644,2021-10-07 14:36:00
6754,"21.135269,72.754578",NL01Q3114_04102021,21.135269,72.754578,2021-10-07 14:42:00
6755,"21.135991,72.75408",NL01Q3114_04102021,21.135991,72.754080,2021-10-07 14:48:00
6756,"21.135416,72.754751",NL01Q3114_04102021,21.135416,72.754751,2021-10-07 14:54:00
6757,NaN,NL01Q3114_04102021,NaN,NaN,2021-10-04 00:00:00

In [43]:
dfframe_format17.isnull().sum()

Lat,Lngt     9
Trip_id      0
Latitude     9
Longitude    9
GPS_dt_tm    0
dtype: int64

In [ ]:
#dfframe_format17.to_excel("17.xlsx")

In [44]:
dfframe_format17 = dfframe_format17.dropna(how='any',axis=0)

In [45]:
dfframe_format17.Trip_id.nunique()

10

In [46]:
dfframe_format17 = dfframe_format17[['Trip_id','Lat,Lngt','Latitude','Longitude','GPS_dt_tm']]

In [47]:
dfframe_format17.Trip_id.value_counts().count()

10

In [49]:
dfframe_format17.shape

(6749, 5)

In [80]:
## format 10 - 1489412
#print(x["'NL01AC2907_02.09.2021.xlsx'"])
df_f10=[]
for path, subdirs, files in os.walk("D:\\Sales Logistic Project\\Decrypted\\"):
    for filename in files:
        fmt_typ = file_frmts[("'" + filename + "'")]   
        if (fmt_typ == "F10"):
            df_tempa=pd.read_excel(os.path.join(path, filename),index_col=None)
            
            df_tempa['Trip_id'] = str(filename)
            #print(df_tempa['Trip_id'].value_counts())
            df_tempa['Packet Time'] = df_tempa['Packet Time'].replace('\n','', regex=True)
            df_tempa['Lat,Lngt'] = df_tempa["Latitude"].astype(str) + df_tempa["Longitude"].astype(str)
            df_tempa['Latitude'] = df_tempa['Latitude'].replace('\n','', regex=True)
            df_tempa['Longitude'] = df_tempa['Longitude'].replace('\n','', regex=True)
        
            #df_tempa[['Latitude', 'Longitude']] = df_tempa['Lat,Lngt'].str.split(',', 1, expand=True)
            #df_tempa['Latitude'] = df_tempa['Latitude'].astype(float)
            #df_tempa['Longitude'] = df_tempa['Longitude'].astype(float)
            #df_tempa['GPS_dt_tm'] = df_tempa['Period'].map(lambda x:"2021"+"-"+str(x)[3:5]+"-"+str(x)[0:2]+" "+str(x)[6:11])
            #df_tempa.drop('Period', axis=1, inplace=True)
            df_tempa['GPS_dt_tm'] = pd.to_datetime(df_tempa['Packet Time'])
            df_f10.append(df_tempa)
            dfframe_format10 = pd.concat(df_f10, axis=0, ignore_index=True)
            #dfframe_format10.Trip_id = dfframe_format10.Trip_id.str.replace('[.xls]', '')
            #dfframe_format10.Trip_id = dfframe_format10.Trip_id.str.replace('[.xlsx]', '')
            df_obj = dfframe_format10.select_dtypes(['object'])
            #dfframe_format10[df_obj.columns] = df_obj.apply(lambda x: x.str.strip())

In [ ]:
#dfframe_format10.to_csv("f10.csv")

In [ ]:
#dfframe_format10 = dfframe_format10.dropna(how='any',axis=0)

In [89]:
dfframe_format10.Trip_id = dfframe_format10.Trip_id.str.replace('[.xls]','')
dfframe_format10.Trip_id = dfframe_format10.Trip_id.str.replace('[.xlsx]','')

In [84]:
dfframe_format10.shape

(1489412, 6)

In [82]:
1489412-1488853

559

In [95]:
dfframe_format10.Trip_id.value_counts()

HR46E0510_02092021     29350
HR46E4249_04092021     27626
HR46E7834_29092021     23929
HR46E2686_25092021     23832
HR46E4411_30092021     21225
                       ...
NL01AA1840_15092021      222
NL010087_08092021        159
HR47B8205_18092021       134
HR63C3828_24082021       127
HR47B5848_16092021        64
Name: Trip_id, Length: 624, dtype: int64

In [93]:
dfframe_format10.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1488853 entries, 0 to 1489410
Data columns (total 6 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Latitude     1488853 non-null  float64
 1   Longitude    1488853 non-null  float64
 2   Packet Time  1488853 non-null  object
 3   Trip_id      1488853 non-null  object
 4   Lat,Lngt     1488853 non-null  object
 5   GPS_dt_tm    1488853 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(3)
memory usage: 79.5+ MB

In [91]:
dfframe_format10 = dfframe_format10.dropna(how='any',axis=0)

In [94]:
dfframe_format10.shape

(1488853, 6)

In [75]:
dfframe_format10.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1486951 entries, 0 to 1489410
Data columns (total 6 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Latitude     1486951 non-null  float64
 1   Longitude    1486951 non-null  float64
 2   Packet Time  1486951 non-null  object
 3   Trip_id      1486951 non-null  object
 4   Lat,Lngt     1486951 non-null  object
 5   GPS_dt_tm    1486951 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(3)
memory usage: 79.4+ MB

In [76]:
#dfframe_format10.to_csv("f10.csv")

In [ ]:
dfframe_format10.Trip_id.nunique()

In [96]:
## format 19
#print(x["'NL01AC2907_02.09.2021.xlsx'"])
df_f19=[]
for path, subdirs, files in os.walk("D:\\Sales Logistic Project\\Decrypted\\"):
    for filename in files:
        fmt_typ = file_frmts[("'" + filename + "'")]   
        if (fmt_typ == "F19"):
            df_tempa=pd.read_excel(os.path.join(path, filename),index_col=None)
            if 'Period' in df_tempa:
            #print(df_tempa['Trip_id'].value_counts())
                #df_tempa['GPS_dt_tm'] = pd.to_datetime(df_tempa['Date'])
            #df_tempa['Period'] = df_tempa['Period'].replace('\n','', regex=True)
            #df_tempa['Lat,Lngt'] = df_tempa['Lat,Lngt'].replace('\n','', regex=True)
                df_tempa[['Latitude', 'Longitude']] = df_tempa['Lat,Lngt'].str.split(',', 1, expand=True)
                df_tempa['Latitude'] = df_tempa['Latitude'].astype(float)
                df_tempa['Longitude'] = df_tempa['Longitude'].astype(float)
                #df_tempa['GPS_dt_tm'] = df_tempa['Period'][0:6].map(lambda x:"2021"+"-"+str(x)[3:5]+"-"+str(x)[0:2]+" "+str(x)[6:11])
                df_tempa['GPS_dt_tm'] = df_tempa['Period'].map(lambda x:"2021"+"-"+str(x)[17:20]+"-"+str(x)[13:16]+" "+str(x)[20:25])
                df_tempa['GPS_dt_tm'] = pd.to_datetime(df_tempa['GPS_dt_tm'])
                df_tempa['LatLong'] = df_tempa['Lat,Lngt']
            else:
                if('Date' in df_tempa):
                    df_tempa['GPS_dt_tm_new'] = pd.to_datetime(df_tempa['Date'])
                    df_tempa['Lat,Lngt'] = df_tempa['LatLong']
                    df_tempa[['Latitude', 'Longitude']] = df_tempa['Lat,Lngt'].str.split(',', 1, expand=True)
                    df_tempa['Latitude'] = df_tempa['Latitude'].astype(float)
                    df_tempa['Longitude'] = df_tempa['Longitude'].astype(float)
                
            df_tempa['Trip_id'] = str(filename)
            df_tempa['Path'] = str(path)
            df_f19.append(df_tempa)
            dfframe_format19 = pd.concat(df_f19, axis=0, ignore_index=True)
            #dfframe_format19.Trip_id = dfframe_format19.Trip_id.str.replace('[.xls]', '')
            #dfframe_format19.Trip_id = dfframe_format19.Trip_id.str.replace('[.xlsx]', '')

In [97]:
dfframe_format19.drop(dfframe_format19[['Date','Period']],axis=1,inplace=True)

In [ ]:
dfframe_format19.Trip_id = dfframe_format19.Trip_id.str.replace('[.xls]', '')
dfframe_format19.Trip_id = dfframe_format19.Trip_id.str.replace('[.xlsx]', '')

In [98]:
dfframe_format19.Trip_id.value_counts()

NL01N7521_17.10.2021.xls     2685
NL017527_04.10.2021.xls      2567
NL01N0020_13.08.2021.xls     2542
NL01AA1361_04.10.2021.xls    2478
NL01AA1895_06.08.2021.xls    2442
                             ...
NL01AA1346_16.10.2021.xls     536
NL01Q2734_01.10.2021.xls      531
NL01AA7753_04.10.2021.xls     529
NL01N9458_30.09.2021.xls      503
NL01AC7384_11.08.2021.xls     123
Name: Trip_id, Length: 133, dtype: int64

In [ ]:
dfframe_format19.head(2)

In [ ]:
dfframe_format19.isnull().sum()

In [ ]:
dfframe_format19.info()

In [ ]:
#dfframe_format19.to_excel("19.xlsx")

In [ ]:
dfframe_format19 = pd.read_excel("D:\\Sales Logistic Project\\F19.xltm")

In [ ]:
dfframe_format19.isnull().sum()

In [ ]:
dfframe_format19.shape

In [ ]:
#181066

In [ ]:
dfframe_format19.isnull().sum()

In [ ]:
dfframe_format19 = dfframe_format19.dropna(how='any',axis=0)

In [ ]:
dfframe_format19.shape

In [ ]:
dfframe_format19.drop(dfframe_format19[['Unnamed: 0','Path']],axis=1,inplace=True)

In [ ]:
dfframe_format19

In [ ]:
dfframe_format19 = dfframe_format19[['Trip_id','Lat,Lngt','Latitude','Longitude','GPS_dt_tm']]

In [ ]:
dfframe_format19

In [ ]:
# format 9

In [ ]:
## format 9
#print(x["'NL01AC2907_02.09.2021.xlsx'"])
df_f9=[]
for path, subdirs, files in os.walk("D:\\Sales Logistic Project\\Decrypted\\"):
    for filename in files:
        fmt_typ = file_frmts[("'" + filename + "'")]   
        if (fmt_typ == "F9"):
            df_tempa=pd.read_excel(os.path.join(path, filename),index_col=None)
            df_tempa.columns = ['Latitude', 'Longitude', 'GPS_dt_tm']
            #if 'Period' in df_tempa:
            #print(df_tempa['Trip_id'].value_counts())
                #df_tempa['GPS_dt_tm'] = pd.to_datetime(df_tempa['Date'])
            #df_tempa['Period'] = df_tempa['Period'].replace('\n','', regex=True)
            #df_tempa['Lat,Lngt'] = df_tempa['Lat,Lngt'].replace('\n','', regex=True)
                #df_tempa[['Latitude', 'Longitude']] = df_tempa['Lat,Lngt'].str.split(',', 1, expand=True)
                #df_tempa['Latitude'] = df_tempa['Latitude'].astype(float)
                #df_tempa['Longitude'] = df_tempa['Longitude'].astype(float)
                #df_tempa['GPS_dt_tm'] = df_tempa['Period'][0:6].map(lambda x:"2021"+"-"+str(x)[3:5]+"-"+str(x)[0:2]+" "+str(x)[6:11])
                #df_tempa['GPS_dt_tm'] = df_tempa['Period'].map(lambda x:"2021"+"-"+str(x)[17:20]+"-"+str(x)[13:16]+" "+str(x)[20:25])
            df_tempa['GPS_dt_tm'] = pd.to_datetime(df_tempa['GPS_dt_tm'])
                #df_tempa['LatLong'] = df_tempa['Lat,Lngt']
            #else:
                #if('Date' in df_tempa):
                    #df_tempa['GPS_dt_tm_new'] = pd.to_datetime(df_tempa['Date'])
                   #df_tempa['Lat,Lngt'] = df_tempa['LatLong']
                    #df_tempa[['Latitude', 'Longitude']] = df_tempa['Lat,Lngt'].str.split(',', 1, expand=True)
                    #df_tempa['Latitude'] = df_tempa['Latitude'].astype(float)
                    #df_tempa['Longitude'] = df_tempa['Longitude'].astype(float)
                
            df_tempa['Trip_id'] = str(filename)
            #df_tempa['Path'] = str(path)
            df_f9.append(df_tempa)
            dfframe_format9 = pd.concat(df_f9, axis=0, ignore_index=True)
            #dfframe_format19.Trip_id = dfframe_format19.Trip_id.str.replace('[.xls]', '')
            #dfframe_format19.Trip_id = dfframe_format19.Trip_id.str.replace('[.xlsx]', '')

In [ ]:
dfframe_format9.info()

In [ ]:
dfframe_format9.isnull().sum()

In [ ]:
dfframe_format9.Trip_id = dfframe_format9.Trip_id.str.replace('[.xls]', '')
dfframe_format9.Trip_id = dfframe_format9.Trip_id.str.replace('[.xlsx]', '')

In [ ]:
dfframe_format9.Trip_id.value_counts().sum()

In [ ]:
dfframe_format9['Lat,Lngt'] = dfframe_format9["Latitude"].astype(str) + dfframe_format9["Longitude"].astype(str)

In [ ]:
dfframe_format9 = dfframe_format9[['Trip_id','Lat,Lngt','Latitude','Longitude','GPS_dt_tm']]

In [ ]:
dfframe_format9

In [ ]:
## format 7
#print(x["'NL01AC2907_02.09.2021.xlsx'"])
df_f7=[]
for path, subdirs, files in os.walk("D:\\Sales Logistic Project\\Decrypted\\"):
    for filename in files:
        fmt_typ = file_frmts[("'" + filename + "'")]   
        if (fmt_typ == "F7"):
            df_tempa=pd.read_excel(os.path.join(path, filename),index_col=None)
            df_tempa['GPS_dt_tm'] = pd.to_datetime(df_tempa['Date'] + ' ' + df_tempa['Time'])
            #df_tempa.columns = ['Latitude', 'Longitude', 'GPS_dt_tm']
            #if 'Period' in df_tempa:
            #print(df_tempa['Trip_id'].value_counts())
                #df_tempa['GPS_dt_tm'] = pd.to_datetime(df_tempa['Date'])
            #df_tempa['Period'] = df_tempa['Period'].replace('\n','', regex=True)
            #df_tempa['Lat,Lngt'] = df_tempa['Lat,Lngt'].replace('\n','', regex=True)
            df_tempa[['Latitude', 'Longitude']] = df_tempa['Lat,Lngt'].str.split(',', 1, expand=True)
            df_tempa['Latitude'] = df_tempa['Latitude'].astype(float)
            df_tempa['Longitude'] = df_tempa['Longitude'].astype(float)
                #df_tempa['GPS_dt_tm'] = df_tempa['Period'][0:6].map(lambda x:"2021"+"-"+str(x)[3:5]+"-"+str(x)[0:2]+" "+str(x)[6:11])
                #df_tempa['GPS_dt_tm'] = df_tempa['Period'].map(lambda x:"2021"+"-"+str(x)[17:20]+"-"+str(x)[13:16]+" "+str(x)[20:25])
            
            #df_tempa['GPS_dt_tm'] = pd.to_datetime(df_tempa['GPS_dt_tm'])
            #df_tempa['LatLong'] = df_tempa['Lat,Lngt']
            #else:
                #if('Date' in df_tempa):
                    #df_tempa['GPS_dt_tm_new'] = pd.to_datetime(df_tempa['Date'])
                   #df_tempa['Lat,Lngt'] = df_tempa['LatLong']
                    #df_tempa[['Latitude', 'Longitude']] = df_tempa['Lat,Lngt'].str.split(',', 1, expand=True)
                    #df_tempa['Latitude'] = df_tempa['Latitude'].astype(float)
                    #df_tempa['Longitude'] = df_tempa['Longitude'].astype(float)
                
            df_tempa['Trip_id'] = str(filename)
            #df_tempa['Path'] = str(path)
            df_f7.append(df_tempa)
            dfframe_format7 = pd.concat(df_f7, axis=0, ignore_index=True)
            dfframe_format7.Trip_id = dfframe_format7.Trip_id.str.replace('[.xls]', '')
            dfframe_format7.Trip_id = dfframe_format7.Trip_id.str.replace('[.xlsx]', '')

In [ ]:
dfframe_format7.info()

In [ ]:
#dfframe_format7.drop(dfframe_format7[['Date','Time']],axis=1,inplace=True)

In [ ]:
dfframe_format7.head(3)

In [ ]:
dfframe_format7 = dfframe_format7[['Trip_id','Lat,Lngt','Latitude','Longitude','GPS_dt_tm']]

In [ ]:
dfframe_format7.Trip_id.value_counts().count()

In [ ]:
dfframe_format7.isnull().sum()

In [ ]:
dfframe_format7.Trip_id.value_counts().sum()

In [ ]:
## format 16
#print(x["'NL01AC2907_02.09.2021.xlsx'"])
df_f16=[]
for path, subdirs, files in os.walk("D:\\Sales Logistic Project\\Decrypted\\"):
    for filename in files:
        fmt_typ = file_frmts[("'" + filename + "'")]   
        if (fmt_typ == "F16"):
            df_tempa=pd.read_excel(os.path.join(path, filename),index_col=None)
            #df_tempa['GPS_dt_time'] = pd.to_datetime(df_tempa['Date'] + ' ' + df_tempa['Time'])
            #df_tempa.columns = ['Latitude', 'Longitude', 'GPS_dt_tm']
            #if 'Period' in df_tempa:
            #print(df_tempa['Trip_id'].value_counts())
                #df_tempa['GPS_dt_tm'] = pd.to_datetime(df_tempa['Date'])
            df_tempa['Period'] = df_tempa['Period'].replace('\n','', regex=True)
            df_tempa['Lat,Lngt'] = df_tempa['Lat,Lngt'].replace('\n','', regex=True)
            df_tempa[['Latitude', 'Longitude']] = df_tempa['Lat,Lngt'].str.split(',', 1, expand=True)
            df_tempa['Latitude'] = df_tempa['Latitude'].astype(float)
            df_tempa['Longitude'] = df_tempa['Longitude'].astype(float)
            #df_tempa['GPS_dt_tm'] = df_tempa['Period'][0:6].map(lambda x:"2021"+"-"+str(x)[3:5]+"-"+str(x)[0:2]+" "+str(x)[6:11])
            #df_tempa['GPS_dt_tm'] = df_tempa['Period'].map(lambda x:"2021"+"-"+str(x)[17:20]+"-"+str(x)[13:16]+" "+str(x)[20:25])
            
            #df_tempa['GPS_dt_tm'] = pd.to_datetime(df_tempa['GPS_dt_tm'])
            #df_tempa['LatLong'] = df_tempa['Lat,Lngt']
            #else:
                #if('Date' in df_tempa):
                    #df_tempa['GPS_dt_tm_new'] = pd.to_datetime(df_tempa['Date'])
                   #df_tempa['Lat,Lngt'] = df_tempa['LatLong']
                    #df_tempa[['Latitude', 'Longitude']] = df_tempa['Lat,Lngt'].str.split(',', 1, expand=True)
                    #df_tempa['Latitude'] = df_tempa['Latitude'].astype(float)
                    #df_tempa['Longitude'] = df_tempa['Longitude'].astype(float)
                
            df_tempa['Trip_id'] = str(filename)
            #df_tempa['Path'] = str(path)
            df_f16.append(df_tempa)
            dfframe_format16 = pd.concat(df_f16, axis=0, ignore_index=True)
            dfframe_format16.Trip_id = dfframe_format16.Trip_id.str.replace('[.xls]', '')
            dfframe_format16.Trip_id = dfframe_format16.Trip_id.str.replace('[.xlsx]', '')

In [ ]:
dfframe_format16

In [ ]:
dfframe_format16['GPS_dt_tm'] = dfframe_format16['Period'].map(lambda x:"2021"+"-"+str(x)[16:19]+"-"+str(x)[13:15]+" " +str(x)[19:25])

In [ ]:
dfframe_format16['GPS_dt_tm'] = pd.to_datetime(dfframe_format16['GPS_dt_tm'])

In [ ]:
dfframe_format16

In [ ]:
dfframe_format16 = dfframe_format16[['Trip_id','Lat,Lngt','Latitude','Longitude','GPS_dt_tm']]

In [ ]:
dfframe_format16.Trip_id.value_counts().count()

In [ ]:
dfframe_format16.Trip_id.value_counts().sum()

In [ ]:
dfframe_format16.shape

In [ ]:
dfframe_format9.isnull().sum()

In [ ]:
dfframe_format16

In [ ]:
dfframe_format16 = dfframe_format16.dropna(how='any',axis=0)

In [ ]:
dfframe_format16.shape

In [ ]:
## format 8
#print(x["'NL01AC2907_02.09.2021.xlsx'"])
df_f8=[]
for path, subdirs, files in os.walk("D:\\Sales Logistic Project\\Decrypted\\"):
    for filename in files:
        fmt_typ = file_frmts[("'" + filename + "'")]   
        if (fmt_typ == "F8"):
            df_tempa=pd.read_excel(os.path.join(path, filename),index_col=None)
            #df_tempa['GPS_dt_time'] = pd.to_datetime(df_tempa['Date'] + ' ' + df_tempa['Time'])
            #df_tempa.columns = ['Latitude', 'Longitude', 'GPS_dt_tm']
            #if 'Period' in df_tempa:
            #print(df_tempa['Trip_id'].value_counts())
                #df_tempa['GPS_dt_tm'] = pd.to_datetime(df_tempa['Date'])
            df_tempa['Period'] = df_tempa['Period'].replace('\n','', regex=True)
            df_tempa['Lat,Lngt'] = df_tempa['Lat,Lngt'].replace('\n','', regex=True)
            df_tempa[['Latitude', 'Longitude']] = df_tempa['Lat,Lngt'].str.split(',', 1, expand=True)
            df_tempa['Latitude'] = df_tempa['Latitude'].astype(float)
            df_tempa['Longitude'] = df_tempa['Longitude'].astype(float)
            #df_tempa['GPS_dt_tm'] = df_tempa['Period'][0:6].map(lambda x:"2021"+"-"+str(x)[3:5]+"-"+str(x)[0:2]+" "+str(x)[6:11])
            df_tempa['GPS_dt_tm'] = df_tempa['Period'].map(lambda x:"2021"+"-"+str(x)[17:20]+"-"+str(x)[13:16]+" "+str(x)[20:25])
            df_tempa['GPS_dt_tm'] = pd.to_datetime(df_tempa['GPS_dt_tm'])
            #df_tempa['LatLong'] = df_tempa['Lat,Lngt']
            #else:
                #if('Date' in df_tempa):
                    #df_tempa['GPS_dt_tm_new'] = pd.to_datetime(df_tempa['Date'])
                   #df_tempa['Lat,Lngt'] = df_tempa['LatLong']
                    #df_tempa[['Latitude', 'Longitude']] = df_tempa['Lat,Lngt'].str.split(',', 1, expand=True)
                    #df_tempa['Latitude'] = df_tempa['Latitude'].astype(float)
                    #df_tempa['Longitude'] = df_tempa['Longitude'].astype(float)
                
            df_tempa['Trip_id'] = str(filename)
            #df_tempa['Path'] = str(path)
            df_f8.append(df_tempa)
            dfframe_format8 = pd.concat(df_f8, axis=0, ignore_index=True)
            dfframe_format8.Trip_id = dfframe_format8.Trip_id.str.replace('[.xls]', '')
            dfframe_format8.Trip_id = dfframe_format8.Trip_id.str.replace('[.xlsx]', '')

In [ ]:
dfframe_format8['Trip_id'].value_counts().sum()

In [ ]:
dfframe_format8.drop('Unnamed: 2',axis=1,inplace=True)

In [ ]:
dfframe_format8

In [ ]:
dfframe_format8 = dfframe_format8.dropna(how='any',axis=0)

In [ ]:
dfframe_format8 = dfframe_format8[['Trip_id','Lat,Lngt','Latitude','Longitude','GPS_dt_tm']]

In [ ]:
dfframe_format8

In [ ]:
dfframe_format8.info()

In [ ]:
## format 4
#print(x["'NL01AC2907_02.09.2021.xlsx'"])
df_f4=[]
for path, subdirs, files in os.walk("D:\\Sales Logistic Project\\Decrypted\\"):
    for filename in files:
        fmt_typ = file_frmts[("'" + filename + "'")]   
        if (fmt_typ == "F4"):
            df_tempa=pd.read_excel(os.path.join(path, filename),index_col=None)
            #df_tempa['GPS_dt_time'] = pd.to_datetime(df_tempa['Date'] + ' ' + df_tempa['Time'])
            #df_tempa.columns = ['Latitude', 'Longitude', 'GPS_dt_tm']
            #if 'Period' in df_tempa:
            #print(df_tempa['Trip_id'].value_counts())
                #df_tempa['GPS_dt_tm'] = pd.to_datetime(df_tempa['Date'])
            #df_tempa['Period'] = df_tempa['Period'].replace('\n','', regex=True)
            #df_tempa['Lat,Lngt'] = df_tempa['Lat,Lngt'].replace('\n','', regex=True)
            #df_tempa[['Latitude', 'Longitude']] = df_tempa['Lat,Lngt'].str.split(',', 1, expand=True)
            #df_tempa['Latitude'] = df_tempa['Latitude'].astype(float)
            #df_tempa['Longitude'] = df_tempa['Longitude'].astype(float)
            #df_tempa['GPS_dt_tm'] = df_tempa['Period'][0:6].map(lambda x:"2021"+"-"+str(x)[3:5]+"-"+str(x)[0:2]+" "+str(x)[6:11])
            #df_tempa['GPS_dt_tm'] = df_tempa['Period'].map(lambda x:"2021"+"-"+str(x)[17:20]+"-"+str(x)[13:16]+" "+str(x)[20:25])
            df_tempa['GPS_dt_tm'] = pd.to_datetime(df_tempa['Time'])
            df_tempa['Lat,Lngt'] = df_tempa["Latitude"].astype(str) + df_tempa["Longitude"].astype(str)
            #df_tempa['LatLong'] = df_tempa['Lat,Lngt']
            #else:
                #if('Date' in df_tempa):
                    #df_tempa['GPS_dt_tm_new'] = pd.to_datetime(df_tempa['Date'])
                   #df_tempa['Lat,Lngt'] = df_tempa['LatLong']
                    #df_tempa[['Latitude', 'Longitude']] = df_tempa['Lat,Lngt'].str.split(',', 1, expand=True)
                    #df_tempa['Latitude'] = df_tempa['Latitude'].astype(float)
                    #df_tempa['Longitude'] = df_tempa['Longitude'].astype(float)
                
            df_tempa['Trip_id'] = str(filename)
            #df_tempa['Path'] = str(path)
            df_f4.append(df_tempa)
            dfframe_format4 = pd.concat(df_f4, axis=0, ignore_index=True)
            dfframe_format4.Trip_id = dfframe_format4.Trip_id.str.replace('[.xls]', '')
            dfframe_format4.Trip_id = dfframe_format4.Trip_id.str.replace('[.xlsx]', '')

In [ ]:
dfframe_format4.Trip_id.value_counts().sum()

In [ ]:
dfframe_format4 = dfframe_format4[['Trip_id','Lat,Lngt','Latitude','Longitude','GPS_dt_tm']]

In [ ]:
dfframe_format4.isnull().sum()

In [ ]:
dfframe_format4

In [ ]:
## format 13
#print(x["'NL01AC2907_02.09.2021.xlsx'"])
df_f13=[]
for path, subdirs, files in os.walk("D:\\Sales Logistic Project\\Decrypted\\"):
    for filename in files:
        fmt_typ = file_frmts[("'" + filename + "'")]   
        if (fmt_typ == "F13"):
            df_tempa=pd.read_excel(os.path.join(path, filename),index_col=None)
            #df_tempa['GPS_dt_time'] = pd.to_datetime(df_tempa['Date'] + ' ' + df_tempa['Time'])
            df_tempa.columns = ['Latitude', 'Longitude', 'GPS_dt_tm']
            #if 'Period' in df_tempa:
            #print(df_tempa['Trip_id'].value_counts())
                #df_tempa['GPS_dt_tm'] = pd.to_datetime(df_tempa['Date'])
            #df_tempa['Period'] = df_tempa['Period'].replace('\n','', regex=True)
            #df_tempa['Lat,Lngt'] = df_tempa['Lat,Lngt'].replace('\n','', regex=True)
            #df_tempa[['Latitude', 'Longitude']] = df_tempa['Lat,Lngt'].str.split(',', 1, expand=True)
            #df_tempa['Latitude'] = df_tempa['Latitude'].astype(float)
            #df_tempa['Longitude'] = df_tempa['Longitude'].astype(float)
            #df_tempa['GPS_dt_tm'] = df_tempa['Period'][0:6].map(lambda x:"2021"+"-"+str(x)[3:5]+"-"+str(x)[0:2]+" "+str(x)[6:11])
            #df_tempa['GPS_dt_tm'] = df_tempa['Period'].map(lambda x:"2021"+"-"+str(x)[17:20]+"-"+str(x)[13:16]+" "+str(x)[20:25])
            df_tempa['Lat,Lngt'] = df_tempa["Latitude"].astype(str) + df_tempa["Longitude"].astype(str)
            df_tempa['GPS_dt_tm'] = pd.to_datetime(df_tempa['GPS_dt_tm'])
            #df_tempa['LatLong'] = df_tempa['Lat,Lngt']
            #else:
                #if('Date' in df_tempa):
                    #df_tempa['GPS_dt_tm_new'] = pd.to_datetime(df_tempa['Date'])
                   #df_tempa['Lat,Lngt'] = df_tempa['LatLong']
                    #df_tempa[['Latitude', 'Longitude']] = df_tempa['Lat,Lngt'].str.split(',', 1, expand=True)
                    #df_tempa['Latitude'] = df_tempa['Latitude'].astype(float)
                    #df_tempa['Longitude'] = df_tempa['Longitude'].astype(float)
                
            df_tempa['Trip_id'] = str(filename)
            #df_tempa['Path'] = str(path)
            df_f13.append(df_tempa)
            dfframe_format13 = pd.concat(df_f13, axis=0, ignore_index=True)
            dfframe_format13.Trip_id = dfframe_format13.Trip_id.str.replace('[.xls]', '')
            dfframe_format13.Trip_id = dfframe_format13.Trip_id.str.replace('[.xlsx]', '')

In [ ]:
dfframe_format13

In [ ]:
dfframe_format13.Trip_id.value_counts()

In [ ]:
dfframe_format13.isnull().sum()

In [ ]:
dfframe_format13 = dfframe_format13[['Trip_id','Lat,Lngt','Latitude','Longitude','GPS_dt_tm']]

In [ ]:
dfframe_format13

In [ ]:
## format 2
#print(x["'NL01AC2907_02.09.2021.xlsx'"])
df_f2=[]
for path, subdirs, files in os.walk("D:\\Sales Logistic Project\\Decrypted\\"):
    for filename in files:
        fmt_typ = file_frmts[("'" + filename + "'")]   
        if (fmt_typ == "F2"):
            df_tempa=pd.read_excel(os.path.join(path, filename),index_col=None)
            #df_tempa['GPS_dt_time'] = pd.to_datetime(df_tempa['Date'] + ' ' + df_tempa['Time'])
            #df_tempa.columns = ['Latitude', 'Longitude', 'GPS_dt_tm']
            #if 'Period' in df_tempa:
            #print(df_tempa['Trip_id'].value_counts())
                #df_tempa['GPS_dt_tm'] = pd.to_datetime(df_tempa['Date'])
            df_tempa['Period'] = df_tempa['Period'].replace('\n','', regex=True)
            df_tempa['Lat,Lngt'] = df_tempa['Lat,Lngt'].replace('\n','', regex=True)
            df_tempa[['Latitude', 'Longitude']] = df_tempa['Lat,Lngt'].str.split(',', 1, expand=True)
            df_tempa['Latitude'] = df_tempa['Latitude'].astype(float)
            df_tempa['Longitude'] = df_tempa['Longitude'].astype(float)
            #df_tempa['GPS_dt_tm'] = df_tempa['Period'][0:6].map(lambda x:"2021"+"-"+str(x)[3:5]+"-"+str(x)[0:2]+" "+str(x)[6:11])
            df_tempa['GPS_dt_tm'] = df_tempa['Period'].map(lambda x:"2021"+"-"+str(x)[17:20]+"-"+str(x)[13:16]+" "+str(x)[20:25])
            df_tempa['GPS_dt_tm'] = pd.to_datetime(df_tempa['GPS_dt_tm'])
            #df_tempa['LatLong'] = df_tempa['Lat,Lngt']
            #else:
                #if('Date' in df_tempa):
                    #df_tempa['GPS_dt_tm_new'] = pd.to_datetime(df_tempa['Date'])
                   #df_tempa['Lat,Lngt'] = df_tempa['LatLong']
                    #df_tempa[['Latitude', 'Longitude']] = df_tempa['Lat,Lngt'].str.split(',', 1, expand=True)
                    #df_tempa['Latitude'] = df_tempa['Latitude'].astype(float)
                    #df_tempa['Longitude'] = df_tempa['Longitude'].astype(float)
                
            df_tempa['Trip_id'] = str(filename)
            #df_tempa['Path'] = str(path)
            df_f2.append(df_tempa)
            dfframe_format2 = pd.concat(df_f2, axis=0, ignore_index=True)
            dfframe_format2.Trip_id = dfframe_format2.Trip_id.str.replace('[.xls]', '')
            dfframe_format2.Trip_id = dfframe_format2.Trip_id.str.replace('[.xlsx]', '')

In [ ]:
dfframe_format2.drop(dfframe_format2[['Unnamed: 2','Unnamed: 3','Unnamed: 4','Unnamed: 5']],axis=1,inplace=True)

In [ ]:
dfframe_format2.shape

In [ ]:
dfframe_format2.isnull().sum()

In [ ]:
dfframe_format2 = dfframe_format2.dropna(how='any',axis=0)

In [ ]:
dfframe_format2.info()

In [ ]:
dfframe_format2 = dfframe_format2[['Trip_id','Lat,Lngt','Latitude','Longitude','GPS_dt_tm']]

In [ ]:
dfframe_format2

In [ ]:
## format 6
#print(x["'NL01AC2907_02.09.2021.xlsx'"])
df_f6=[]
for path, subdirs, files in os.walk("D:\\Sales Logistic Project\\Decrypted\\"):
    for filename in files:
        fmt_typ = file_frmts[("'" + filename + "'")]   
        if (fmt_typ == "F6"):
            df_tempa=pd.read_excel(os.path.join(path, filename),index_col=None)
            df_tempa['GPS_dt_tm'] = pd.to_datetime(df_tempa['Date'] + ' ' + df_tempa['Time'])
            #df_tempa.columns = ['Latitude', 'Longitude', 'GPS_dt_tm']
            #if 'Period' in df_tempa:
            #print(df_tempa['Trip_id'].value_counts())
                #df_tempa['GPS_dt_tm'] = pd.to_datetime(df_tempa['Date'])
            #df_tempa['Period'] = df_tempa['Period'].replace('\n','', regex=True)
            df_tempa['Lat,Lngt'] = df_tempa['Lat,Lngt'].replace('\n','', regex=True)
            df_tempa[['Latitude', 'Longitude']] = df_tempa['Lat,Lngt'].str.split(',', 1, expand=True)
            df_tempa['Latitude'] = df_tempa['Latitude'].astype(float)
            df_tempa['Longitude'] = df_tempa['Longitude'].astype(float)
            #df_tempa['GPS_dt_tm'] = df_tempa['Period'][0:6].map(lambda x:"2021"+"-"+str(x)[3:5]+"-"+str(x)[0:2]+" "+str(x)[6:11])
            #df_tempa['GPS_dt_tm'] = df_tempa['Period'].map(lambda x:"2021"+"-"+str(x)[17:20]+"-"+str(x)[13:16]+" "+str(x)[20:25])
            ##df_tempa['GPS_dt_tm'] = pd.to_datetime(df_tempa['GPS_dt_tm'])
            #df_tempa['LatLong'] = df_tempa['Lat,Lngt']
            #else:
                #if('Date' in df_tempa):
                    #df_tempa['GPS_dt_tm_new'] = pd.to_datetime(df_tempa['Date'])
                   #df_tempa['Lat,Lngt'] = df_tempa['LatLong']
                    #df_tempa[['Latitude', 'Longitude']] = df_tempa['Lat,Lngt'].str.split(',', 1, expand=True)
                    #df_tempa['Latitude'] = df_tempa['Latitude'].astype(float)
                    #df_tempa['Longitude'] = df_tempa['Longitude'].astype(float)
                
            df_tempa['Trip_id'] = str(filename)
            #df_tempa['Path'] = str(path)
            df_f6.append(df_tempa)
            dfframe_format6 = pd.concat(df_f6, axis=0, ignore_index=True)
            dfframe_format6.Trip_id = dfframe_format6.Trip_id.str.replace('[.xls]', '')
            dfframe_format6.Trip_id = dfframe_format6.Trip_id.str.replace('[.xlsx]', '')

In [ ]:
dfframe_format6

In [ ]:
dfframe_format6.info()

In [ ]:
dfframe_format6.drop(dfframe_format6[['Vehicle','Date','Time']], axis=1, inplace=True)
#dfframe_format2.drop(dfframe_format2[['Unnamed: 2','Unnamed: 3','Unnamed: 4','Unnamed: 5']],axis=1,inplace=True)

In [ ]:
dfframe_format6 = dfframe_format6[['Trip_id','Lat,Lngt','Latitude','Longitude','GPS_dt_tm']]

In [ ]:
dfframe_format6

In [ ]:
dfframe_format6.isnull().sum()

In [ ]:
dfframe_format6.Trip_id.value_counts().sum()

In [ ]:
## format 14
#print(x["'NL01AC2907_02.09.2021.xlsx'"])
df_f14=[]
for path, subdirs, files in os.walk("D:\\Sales Logistic Project\\Decrypted\\"):
    for filename in files:
        fmt_typ = file_frmts[("'" + filename + "'")]   
        if (fmt_typ == "F14"):
            df_tempa=pd.read_excel(os.path.join(path, filename),index_col=None)
            df_tempa = df_tempa[1:]
            #df_tempa['GPS_dt_time'] = pd.to_datetime(df_tempa['Date'] + ' ' + df_tempa['Time'])
            df_tempa.columns = ['Latitude', 'Longitude', 'GPS_dt_tm']
            #if 'Period' in df_tempa:
            #print(df_tempa['Trip_id'].value_counts())
                #df_tempa['GPS_dt_tm'] = pd.to_datetime(df_tempa['Date'])
            #df_tempa['Period'] = df_tempa['Period'].replace('\n','', regex=True)
            #df_tempa['Lat,Lngt'] = df_tempa['Lat,Lngt'].replace('\n','', regex=True)
            #df_tempa[['Latitude', 'Longitude']] = df_tempa['Lat,Lngt'].str.split(',', 1, expand=True)
            #df_tempa['Latitude'] = df_tempa['Latitude'].astype(float)
            #df_tempa['Longitude'] = df_tempa['Longitude'].astype(float)
            #df_tempa['GPS_dt_tm'] = df_tempa['Period'][0:6].map(lambda x:"2021"+"-"+str(x)[3:5]+"-"+str(x)[0:2]+" "+str(x)[6:11])
            #df_tempa['GPS_dt_tm'] = df_tempa['Period'].map(lambda x:"2021"+"-"+str(x)[17:20]+"-"+str(x)[13:16]+" "+str(x)[20:25])
            ##df_tempa['GPS_dt_tm'] = pd.to_datetime(df_tempa['GPS_dt_tm'])
            df_tempa['Lat,Lngt'] = df_tempa["Latitude"].astype(str) + df_tempa["Longitude"].astype(str)
            df_tempa['GPS_dt_tm'] = pd.to_datetime(df_tempa['GPS_dt_tm'])
            #df_tempa['LatLong'] = df_tempa['Lat,Lngt']
            #else:
                #if('Date' in df_tempa):
                    #df_tempa['GPS_dt_tm_new'] = pd.to_datetime(df_tempa['Date'])
                   #df_tempa['Lat,Lngt'] = df_tempa['LatLong']
                    #df_tempa[['Latitude', 'Longitude']] = df_tempa['Lat,Lngt'].str.split(',', 1, expand=True)
                    #df_tempa['Latitude'] = df_tempa['Latitude'].astype(float)
                    #df_tempa['Longitude'] = df_tempa['Longitude'].astype(float)
                
            df_tempa['Trip_id'] = str(filename)
            #df_tempa['Path'] = str(path)
            df_f14.append(df_tempa)
            dfframe_format14 = pd.concat(df_f14, axis=0, ignore_index=True)
            dfframe_format14.Trip_id = dfframe_format14.Trip_id.str.replace('[.xls]', '')
            dfframe_format14.Trip_id = dfframe_format14.Trip_id.str.replace('[.xlsx]', '')

In [ ]:
dfframe_format14

In [ ]:
dfframe_format14.isnull().sum()

In [ ]:
dfframe_format14 = dfframe_format14[['Trip_id','Lat,Lngt','Latitude','Longitude','GPS_dt_tm']]

In [ ]:
## format 5
#print(x["'NL01AC2907_02.09.2021.xlsx'"])
df_f5=[]
for path, subdirs, files in os.walk("D:\\Sales Logistic Project\\Decrypted\\"):
    for filename in files:
        fmt_typ = file_frmts[("'" + filename + "'")]   
        if (fmt_typ == "F5"):
            df_tempa=pd.read_excel(os.path.join(path, filename),index_col=None)
            #df_tempa = df_tempa[1:]
            #df_tempa['GPS_dt_time'] = pd.to_datetime(df_tempa['Date'] + ' ' + df_tempa['Time'])
            df_tempa.columns = ['License_Number','Latitude', 'Longitude', 'GPS_dt_tm']
            #if 'Period' in df_tempa:
            #print(df_tempa['Trip_id'].value_counts())
                #df_tempa['GPS_dt_tm'] = pd.to_datetime(df_tempa['Date'])
            #df_tempa['Period'] = df_tempa['Period'].replace('\n','', regex=True)
            #df_tempa['Lat,Lngt'] = df_tempa['Lat,Lngt'].replace('\n','', regex=True)
            #df_tempa[['Latitude', 'Longitude']] = df_tempa['Lat,Lngt'].str.split(',', 1, expand=True)
            #df_tempa['Latitude'] = df_tempa['Latitude'].astype(float)
            #df_tempa['Longitude'] = df_tempa['Longitude'].astype(float)
            #df_tempa['GPS_dt_tm'] = df_tempa['Period'][0:6].map(lambda x:"2021"+"-"+str(x)[3:5]+"-"+str(x)[0:2]+" "+str(x)[6:11])
            #df_tempa['GPS_dt_tm'] = df_tempa['Period'].map(lambda x:"2021"+"-"+str(x)[17:20]+"-"+str(x)[13:16]+" "+str(x)[20:25])
            ##df_tempa['GPS_dt_tm'] = pd.to_datetime(df_tempa['GPS_dt_tm'])
            df_tempa['Lat,Lngt'] = df_tempa["Latitude"].astype(str) + df_tempa["Longitude"].astype(str)
            df_tempa['GPS_dt_tm'] = pd.to_datetime(df_tempa['GPS_dt_tm'])
            #df_tempa['LatLong'] = df_tempa['Lat,Lngt']
            #else:
                #if('Date' in df_tempa):
                    #df_tempa['GPS_dt_tm_new'] = pd.to_datetime(df_tempa['Date'])
                   #df_tempa['Lat,Lngt'] = df_tempa['LatLong']
                    #df_tempa[['Latitude', 'Longitude']] = df_tempa['Lat,Lngt'].str.split(',', 1, expand=True)
                    #df_tempa['Latitude'] = df_tempa['Latitude'].astype(float)
                    #df_tempa['Longitude'] = df_tempa['Longitude'].astype(float)
                
            df_tempa['Trip_id'] = str(filename)
            #df_tempa['Path'] = str(path)
            df_f5.append(df_tempa)
            dfframe_format5 = pd.concat(df_f5, axis=0, ignore_index=True)
            dfframe_format5.Trip_id = dfframe_format5.Trip_id.str.replace('[.xls]', '')
            dfframe_format5.Trip_id = dfframe_format5.Trip_id.str.replace('[.xlsx]', '')

In [ ]:
dfframe_format5

In [ ]:
dfframe_format5.drop(['License_Number'],axis=1,inplace=True)

In [ ]:
dfframe_format5 = dfframe_format5[['Trip_id','Lat,Lngt','Latitude','Longitude','GPS_dt_tm']]

In [ ]:
dfframe_format5.info()

In [ ]:
dfframe_format5.isnull().sum()

## format 3
#print(x["'NL01AC2907_02.09.2021.xlsx'"])
df_f1=[]
for path, subdirs, files in os.walk("D:\\Sales Logistic Project\\Decrypted\\"):
    for filename in files:
        fmt_typ = file_frmts[("'" + filename + "'")]   
        if (fmt_typ == "F1"):
            df_tempa=pd.read_excel(os.path.join(path, filename),index_col=None)
            #df_tempa['GPS_dt_time'] = pd.to_datetime(df_tempa['Date'] + ' ' + df_tempa['Time'])
            #df_tempa.columns = ['Latitude', 'Longitude', 'GPS_dt_tm']
            #if 'Period' in df_tempa:
            #print(df_tempa['Trip_id'].value_counts())
                #df_tempa['GPS_dt_tm'] = pd.to_datetime(df_tempa['Date'])
            df_tempa['Period'] = df_tempa['Period'].replace('\n','', regex=True)
            df_tempa['Lat,Lngt'] = df_tempa['Lat,Lngt'].replace('\n','', regex=True)
            df_tempa[['Latitude', 'Longitude']] = df_tempa['Lat,Lngt'].str.split(',', 1, expand=True)
            df_tempa['Latitude'] = df_tempa['Latitude'].astype(float)
            df_tempa['Longitude'] = df_tempa['Longitude'].astype(float)
            #df_tempa['GPS_dt_tm'] = df_tempa['Period'][0:6].map(lambda x:"2021"+"-"+str(x)[3:5]+"-"+str(x)[0:2]+" "+str(x)[6:11])
            df_tempa['GPS_dt_tm'] = df_tempa['Period'].map(lambda x:"2021"+"-"+str(x)[17:20]+"-"+str(x)[13:16]+" "+str(x)[20:25])
            df_tempa['GPS_dt_tm'] = pd.to_datetime(df_tempa['Packet Time'])
            #df_tempa['Lat,Lngt'] = df_tempa["Latitude"].astype(str) + df_tempa["Longitude"].astype(str)
            #df_tempa['LatLong'] = df_tempa['Lat,Lngt']
            #else:
                #if('Date' in df_tempa):
                    #df_tempa['GPS_dt_tm_new'] = pd.to_datetime(df_tempa['Date'])
                   #df_tempa['Lat,Lngt'] = df_tempa['LatLong']
                    #df_tempa[['Latitude', 'Longitude']] = df_tempa['Lat,Lngt'].str.split(',', 1, expand=True)
                    #df_tempa['Latitude'] = df_tempa['Latitude'].astype(float)
                    #df_tempa['Longitude'] = df_tempa['Longitude'].astype(float)
                
            df_tempa['Trip_id'] = str(filename)
            #df_tempa['Path'] = str(path)
            df_f1.append(df_tempa)
            dfframe_format1 = pd.concat(df_f1, axis=0, ignore_index=True)
            dfframe_format1.Trip_id = dfframe_format1.Trip_id.str.replace('[.xls]', '')
            dfframe_format1.Trip_id = dfframe_format1.Trip_id.str.replace('[.xlsx]', '')

In [ ]:
## format 1
#print(x["'NL01AC2907_02.09.2021.xlsx'"])
df_f1=[]
for path, subdirs, files in os.walk("D:\\Sales Logistic Project\\Decrypted\\"):
    for filename in files:
        fmt_typ = file_frmts[("'" + filename + "'")]   
        if (fmt_typ == "F1"):
            df_tempa=pd.read_excel(os.path.join(path, filename),index_col=None)
            #df_tempa = df_tempa[1:]
            #df_tempa['GPS_dt_time'] = pd.to_datetime(df_tempa['Date'] + ' ' + df_tempa['Time'])
            #df_tempa.columns = ['License_Number','Latitude', 'Longitude', 'GPS_dt_tm']
            #if 'Period' in df_tempa:
            #print(df_tempa['Trip_id'].value_counts())
                #df_tempa['GPS_dt_tm'] = pd.to_datetime(df_tempa['Date'])
            df_tempa['Period'] = df_tempa['Period'].replace('\n','', regex=True)
            df_tempa['Lat,Lngt'] = df_tempa['Lat,Lngt'].replace('\n','', regex=True)
            df_tempa[['Latitude', 'Longitude']] = df_tempa['Lat,Lngt'].str.split(',', 1, expand=True)
            df_tempa['Latitude'] = df_tempa['Latitude'].astype(float)
            df_tempa['Longitude'] = df_tempa['Longitude'].astype(float)
            df_tempa['GPS_dt_tm'] = df_tempa['Period'].map(lambda x:"2021"+"-"+str(x)[3:5]+"-"+str(x)[0:2]+" "+str(x)[6:11])
            #df_tempa['GPS_dt_tm'] = df_tempa['Period'].map(lambda x:"2021"+"-"+str(x)[17:20]+"-"+str(x)[13:16]+" "+str(x)[20:25])
            ##df_tempa['GPS_dt_tm'] = pd.to_datetime(df_tempa['GPS_dt_tm'])
            df_tempa['GPS_dt_tm'] = pd.to_datetime(df_tempa['GPS_dt_tm'])
            #df_tempa['LatLong'] = df_tempa['Lat,Lngt']
            #else:
                #if('Date' in df_tempa):
                    #df_tempa['GPS_dt_tm_new'] = pd.to_datetime(df_tempa['Date'])
                   #df_tempa['Lat,Lngt'] = df_tempa['LatLong']
                    #df_tempa[['Latitude', 'Longitude']] = df_tempa['Lat,Lngt'].str.split(',', 1, expand=True)
                    #df_tempa['Latitude'] = df_tempa['Latitude'].astype(float)
                    #df_tempa['Longitude'] = df_tempa['Longitude'].astype(float)
                
            df_tempa['Trip_id'] = str(filename)
            #df_tempa['Path'] = str(path)

In [ ]:
df_f1.append(df_tempa)
dfframe_format1 = pd.concat(df_f1, axis=0, ignore_index=True)
dfframe_format1.Trip_id = dfframe_format1.Trip_id.str.replace('[.xls]', '')
dfframe_format1.Trip_id = dfframe_format1.Trip_id.str.replace('[.xlsx]', '')

In [ ]:
dfframe_format1.info()

In [ ]:
dfframe_format1 = dfframe_format1.dropna(how='any',axis=0)

In [ ]:
dfframe_format1.info()

In [ ]:
dfframe_format1.Trip_id.value_counts()

In [ ]:
dfframe_format1 = dfframe_format1[['Trip_id','Lat,Lngt','Latitude','Longitude','GPS_dt_tm']]

In [ ]:
dfframe_format1.info()

In [ ]:
dfframe_format1

In [ ]:
## format 3
#print(x["'NL01AC2907_02.09.2021.xlsx'"])
df_f3=[]
for path, subdirs, files in os.walk("D:\\Sales Logistic Project\\Decrypted\\"):
    for filename in files:
        fmt_typ = file_frmts[("'" + filename + "'")]   
        if (fmt_typ == "F3"):
            df_tempa=pd.read_excel(os.path.join(path, filename),index_col=None)
            #df_tempa['GPS_dt_time'] = pd.to_datetime(df_tempa['Date'] + ' ' + df_tempa['Time'])
            #df_tempa.columns = ['Latitude', 'Longitude', 'GPS_dt_tm']
            #if 'Period' in df_tempa:
            #print(df_tempa['Trip_id'].value_counts())
                #df_tempa['GPS_dt_tm'] = pd.to_datetime(df_tempa['Date'])
            #df_tempa['Period'] = df_tempa['Period'].replace('\n','', regex=True)
            #df_tempa['Lat,Lngt'] = df_tempa['Lat,Lngt'].replace('\n','', regex=True)
            #df_tempa[['Latitude', 'Longitude']] = df_tempa['Lat,Lngt'].str.split(',', 1, expand=True)
            #df_tempa['Latitude'] = df_tempa['Latitude'].astype(float)
            #df_tempa['Longitude'] = df_tempa['Longitude'].astype(float)
            #df_tempa['GPS_dt_tm'] = df_tempa['Period'][0:6].map(lambda x:"2021"+"-"+str(x)[3:5]+"-"+str(x)[0:2]+" "+str(x)[6:11])
            #df_tempa['GPS_dt_tm'] = df_tempa['Period'].map(lambda x:"2021"+"-"+str(x)[17:20]+"-"+str(x)[13:16]+" "+str(x)[20:25])
            df_tempa['GPS_dt_tm'] = pd.to_datetime(df_tempa['Packet Time'])
            df_tempa['Lat,Lngt'] = df_tempa["Latitude"].astype(str) + df_tempa["Longitude"].astype(str)
            #df_tempa['LatLong'] = df_tempa['Lat,Lngt']
            #else:
                #if('Date' in df_tempa):
                    #df_tempa['GPS_dt_tm_new'] = pd.to_datetime(df_tempa['Date'])
                   #df_tempa['Lat,Lngt'] = df_tempa['LatLong']
                    #df_tempa[['Latitude', 'Longitude']] = df_tempa['Lat,Lngt'].str.split(',', 1, expand=True)
                    #df_tempa['Latitude'] = df_tempa['Latitude'].astype(float)
                    #df_tempa['Longitude'] = df_tempa['Longitude'].astype(float)
                
            df_tempa['Trip_id'] = str(filename)
            #df_tempa['Path'] = str(path)
            df_f3.append(df_tempa)
            dfframe_format3 = pd.concat(df_f3, axis=0, ignore_index=True)
            dfframe_format3.Trip_id = dfframe_format3.Trip_id.str.replace('[.xls]', '')
            dfframe_format3.Trip_id = dfframe_format3.Trip_id.str.replace('[.xlsx]', '')

In [ ]:
dfframe_format3.Trip_id.value_counts()

In [ ]:
dfframe_format3.isnull().sum()

In [ ]:
dfframe_format3.drop(dfframe_format3[['Unnamed: 0','Truck No']],axis=1,inplace=True)

In [ ]:
dfframe_format3.isnull().sum()

In [ ]:
dfframe_format3 = dfframe_format3.dropna(how='any',axis=0)

In [ ]:
dfframe_format3.shape

In [ ]:
dfframe_format3

In [ ]:
dfframe_format3 = dfframe_format3[['Trip_id','Lat,Lngt','Latitude','Longitude','GPS_dt_tm']]

In [ ]:
## format 11
#print(x["'NL01AC2907_02.09.2021.xlsx'"])
df_f11=[]
for path, subdirs, files in os.walk("D:\\Sales Logistic Project\\Decrypted\\"):
    for filename in files:
        fmt_typ = file_frmts[("'" + filename + "'")]   
        if (fmt_typ == "F11"):
            df_tempa=pd.read_excel(os.path.join(path, filename),index_col=None)
            #df_tempa['GPS_dt_time'] = pd.to_datetime(df_tempa['Date'] + ' ' + df_tempa['Time'])
            #df_tempa.columns = ['Latitude', 'Longitude', 'GPS_dt_tm']
            #if 'Period' in df_tempa:
            #print(df_tempa['Trip_id'].value_counts())
                #df_tempa['GPS_dt_tm'] = pd.to_datetime(df_tempa['Date'])
            #df_tempa['Period'] = df_tempa['Period'].replace('\n','', regex=True)
            #df_tempa['Lat,Lngt'] = df_tempa['Lat,Lngt'].replace('\n','', regex=True)
            #df_tempa[['Latitude', 'Longitude']] = df_tempa['Lat,Lngt'].str.split(',', 1, expand=True)
            #df_tempa['Latitude'] = df_tempa['Latitude'].astype(float)
            #df_tempa['Longitude'] = df_tempa['Longitude'].astype(float)
            #df_tempa['GPS_dt_tm'] = df_tempa['Period'][0:6].map(lambda x:"2021"+"-"+str(x)[3:5]+"-"+str(x)[0:2]+" "+str(x)[6:11])
            #df_tempa['GPS_dt_tm'] = df_tempa['Period'].map(lambda x:"2021"+"-"+str(x)[17:20]+"-"+str(x)[13:16]+" "+str(x)[20:25])
            df_tempa['GPS_dt_tm'] = pd.to_datetime(df_tempa['Packet Time'])
            df_tempa['Lat,Lngt'] = df_tempa["Latitude"].astype(str) + df_tempa["Longitude"].astype(str)
            #df_tempa['LatLong'] = df_tempa['Lat,Lngt']
            #else:
                #if('Date' in df_tempa):
                    #df_tempa['GPS_dt_tm_new'] = pd.to_datetime(df_tempa['Date'])
                   #df_tempa['Lat,Lngt'] = df_tempa['LatLong']
                    #df_tempa[['Latitude', 'Longitude']] = df_tempa['Lat,Lngt'].str.split(',', 1, expand=True)
                    #df_tempa['Latitude'] = df_tempa['Latitude'].astype(float)
                    #df_tempa['Longitude'] = df_tempa['Longitude'].astype(float)
                
            df_tempa['Trip_id'] = str(filename)
            #df_tempa['Path'] = str(path)
            df_f11.append(df_tempa)
            dfframe_format11 = pd.concat(df_f11, axis=0, ignore_index=True)
            dfframe_format11.Trip_id = dfframe_format11.Trip_id.str.replace('[.xls]', '')
            dfframe_format11.Trip_id = dfframe_format11.Trip_id.str.replace('[.xlsx]', '')

In [ ]:
dfframe_format11

In [ ]:
dfframe_format11 = dfframe_format11[['Trip_id','Lat,Lngt','Latitude','Longitude','GPS_dt_tm']]

In [ ]:
dfframe_format11.info()

In [ ]:
dfframe_format11.Trip_id.value_counts()

In [ ]:
dfframe_format11 = dfframe_format11.dropna(how='any',axis=0)

In [ ]:
dfframe_format11.shape

In [ ]:
## format 12
#print(x["'NL01AC2907_02.09.2021.xlsx'"])
df_f12=[]
for path, subdirs, files in os.walk("D:\\Sales Logistic Project\\Decrypted\\"):
    for filename in files:
        fmt_typ = file_frmts[("'" + filename + "'")]   
        if (fmt_typ == "F12"):
            df_tempa=pd.read_excel(os.path.join(path, filename),index_col=None)
            #df_tempa['GPS_dt_time'] = pd.to_datetime(df_tempa['Date'] + ' ' + df_tempa['Time'])
            #df_tempa.columns = ['Latitude', 'Longitude', 'GPS_dt_tm']
            #if 'Period' in df_tempa:
            #print(df_tempa['Trip_id'].value_counts())
                #df_tempa['GPS_dt_tm'] = pd.to_datetime(df_tempa['Date'])
            #df_tempa['Period'] = df_tempa['Period'].replace('\n','', regex=True)
            #df_tempa['Lat,Lngt'] = df_tempa['Lat,Lngt'].replace('\n','', regex=True)
            #df_tempa[['Latitude', 'Longitude']] = df_tempa['Lat,Lngt'].str.split(',', 1, expand=True)
            #df_tempa['Latitude'] = df_tempa['Latitude'].astype(float)
            #df_tempa['Longitude'] = df_tempa['Longitude'].astype(float)
            #df_tempa['GPS_dt_tm'] = df_tempa['Period'][0:6].map(lambda x:"2021"+"-"+str(x)[3:5]+"-"+str(x)[0:2]+" "+str(x)[6:11])
            #df_tempa['GPS_dt_tm'] = df_tempa['Period'].map(lambda x:"2021"+"-"+str(x)[17:20]+"-"+str(x)[13:16]+" "+str(x)[20:25])
            df_tempa['GPS_dt_tm'] = pd.to_datetime(df_tempa['Time'])
            df_tempa['Lat,Lngt'] = df_tempa["Latitude"].astype(str) + df_tempa["Longitude"].astype(str)
            #df_tempa['LatLong'] = df_tempa['Lat,Lngt']
            #else:
                #if('Date' in df_tempa):
                    #df_tempa['GPS_dt_tm_new'] = pd.to_datetime(df_tempa['Date'])
                   #df_tempa['Lat,Lngt'] = df_tempa['LatLong']
                    #df_tempa[['Latitude', 'Longitude']] = df_tempa['Lat,Lngt'].str.split(',', 1, expand=True)
                    #df_tempa['Latitude'] = df_tempa['Latitude'].astype(float)
                    #df_tempa['Longitude'] = df_tempa['Longitude'].astype(float)
                
            df_tempa['Trip_id'] = str(filename)
            #df_tempa['Path'] = str(path)
            df_f12.append(df_tempa)
            dfframe_format12 = pd.concat(df_f12, axis=0, ignore_index=True)
            dfframe_format12.Trip_id = dfframe_format12.Trip_id.str.replace('[.xls]', '')
            dfframe_format12.Trip_id = dfframe_format12.Trip_id.str.replace('[.xlsx]', '')

In [ ]:
dfframe_format12

In [ ]:
dfframe_format12 = dfframe_format12[['Trip_id','Lat,Lngt','Latitude','Longitude','GPS_dt_tm']]

In [ ]:
dfframe_format12.Trip_id.value_counts().sum()

In [ ]:
dfframe_format12.isnull().sum()

In [ ]:
# concat - datasets

In [ ]:
pdList = [dfframe_format1, dfframe_format2,dfframe_format3,dfframe_format4,dfframe_format5,dfframe_format6,dfframe_format7,dfframe_format8,dfframe_format9,dfframe_format10,dfframe_format11,dfframe_format12,dfframe_format13,dfframe_format14,dfframe_format16,dfframe_format17,dfframe_format18,dfframe_format19]  # List of your dataframes
master_data = pd.concat(pdList)

In [ ]:
master_data.drop('Packet Time',axis = 1,inplace=True)

In [ ]:
master_data.shape

In [ ]:
master_data

In [ ]:
master_data.Trip_id.value_counts()

In [ ]:
master_data.Trip_id.nunique()

In [ ]:
#pdList = []
#pdList.extend(value for name, value in locals().items() if name.startswith('dfframe_'))

In [ ]:
#master_data = pd.DataFrame(pdList)

In [ ]:
#master_data

In [ ]:
## Data Consistency

In [ ]:
master_data['GPS_dt_tm'] = pd.to_datetime(master_data['GPS_dt_tm'])

In [ ]:
#master_data.iloc[np.where(master_data['GPS_dt_tm']=='2021-1--20 0-17 ')]

In [ ]:
master_data['Time_diff'] = [x.iloc[-1] - x.iloc[0] for x in master_data['GPS_dt_tm'].rolling(2) if len(x)>0]

In [ ]:
master_data.dtypes

In [ ]:
#diff_v_counts = master_data['Time_diff'].value_counts()

In [ ]:
master_data.shape

In [ ]:
#d_percent_count = master_data.Time_diff.value_counts(normalize=True).mul(100).round(4).astype(str) + '%'

In [ ]:
#d_percent_count

In [ ]:
master_data.isnull().sum()

In [ ]:
master_data.Trip_id.value_counts().count()

In [ ]:
master_data.head(2)

In [ ]:
master_data.Trip_id.value_counts()

In [ ]:
#master_data.describe(include='O')

In [ ]:
master_data.Trip_id = master_data.Trip_id.str.replace('[.xls]', '')
master_data.Trip_id = master_data.Trip_id.str.replace('[.xlsx]', '')

# Master_City_Master/ Master_city_Working

# Single City - Single/Multiple dealer

In [ ]:
master_city_m = pd.read_excel("D:\\Sales Logistic Project\\Master_Single_City.xltm",sheet_name='Master')

In [ ]:
master_city_w = pd.read_excel("D:\\Sales Logistic Project\\Master_Single_City.xltm",sheet_name='working')

In [ ]:
master_city_m = master_city_m[['UNIQUE ID','City code','Dealer code',2,3,4]]

In [ ]:
master_city_m.columns = ['Trip_id_m','City_Code','Dealer_code1','Dealer_code2','Dealer_code3','Dealer_code4']

In [ ]:
master_city_m

In [ ]:
master_city_m.Trip_id = master_city_m.Trip_id_m.str.replace('[.xls]', '')
master_city_m.Trip_id = master_city_m.Trip_id_m.str.replace('[.xlsx]', '')

In [ ]:
master_city_m.fillna('', inplace=True)

In [ ]:
master_city_m['Dealer'] = master_city_m['Dealer_code1']+master_city_m['Dealer_code2']+master_city_m['Dealer_code3']+master_city_m['Dealer_code4']

In [ ]:
master_city_m

In [ ]:
master_city_w

In [ ]:
master_data_city_m_merge = pd.merge(master_data, master_city_m['Trip_id_m'], left_on='Trip_id', right_on = 'Trip_id_m', how = 'outer',indicator=True)
master_data_city_m_merge.shape

In [ ]:
master_data_city_m_merge

In [ ]:
## Multiple City

In [ ]:
mult_master_city = pd.read_excel("D:\\Sales Logistic Project\\Multiple_City.xltm",sheet_name='Multi city')

In [ ]:
mult_master_city

In [ ]:
mult_master_city = mult_master_city[['UNIQUE ID','Dealer code',2,3,4,5]]

In [ ]:
mult_master_city.columns = ['Trip_id_m','Dealer_Code1','Dealer_code2','Dealer_code3','Dealer_code4','Dealer_code5']

In [ ]:
mult_master_city.Trip_id_m = mult_master_city.Trip_id_m.str.replace('[.]', '')

In [ ]:
mult_master_city.Trip_id_m

In [ ]:
mult_master_city

In [ ]:
master_city_m

In [ ]:
master_city_m

### DECEMBER, 10

In [ ]:
df_single_city = pd.read_excel("D:\\Sales Logistic Project\single_city.xltm")

In [ ]:
df_single_city

In [ ]:
df2 = df_single_city[df_single_city['ranks']==1]

In [ ]:
df3 = df_single_city.iloc[np.where(df_single_city.ranks==1)]

In [ ]:
df3

In [ ]:
df2.ID = df2.ID.str.replace('[.]', '')

In [ ]:
master_data

In [ ]:
df2.ID.value_counts()

In [ ]:
 
final_data = pd.merge(master_data, df2, how = 'inner', left_on = 'Trip_id', right_on = 'ID')
print(final_data.shape)

In [ ]:
final_data.to_excel("Final_data.xlsx")

In [ ]:
final_data.shape

In [ ]:
f2 = final_data[final_data['Trip_id']=='NL01K8951_04092021']

In [ ]:
#f2

# SINGLE CITY - 13-12-21

In [ ]:
df_sc = pd.read_excel("D:\\Sales Logistic Project\sc1321.xltm")

In [ ]:
df_sc

In [ ]:
df_sc.drop('Unnamed: 0',axis=1,inplace=True)

In [ ]:
df_single_city = df_sc[df_sc['ranks']==1]

In [ ]:
df_single_city

In [ ]:
df_single_city.ID = df_single_city.ID.str.replace('[.]', '')

In [ ]:
df_single_city.ID.value_counts()

In [ ]:
final_single_city_data = pd.merge(master_data, df_single_city, how = 'inner', left_on = 'Trip_id', right_on = 'ID')
print(final_data.shape)

In [ ]:
final_single_city_data.to_excel("single_city.xlsx")

In [ ]:
final_single_city_data

In [ ]:
def haversine_distance(lat1, lon1, lat2, lon2):
   r = 6371
   phi1 = np.radians(lat1)
   phi2 = np.radians(lat2)
   delta_phi = np.radians(lat2 - lat1)
   delta_lambda = np.radians(lon2 - lon1)
   a = np.sin(delta_phi / 2)**2 + np.cos(phi1) * np.cos(phi2) *   np.sin(delta_lambda / 2)**2
   res = r * (2 * np.arctan2(np.sqrt(a), np.sqrt(1 - a)))
   return np.round(res, 2)

In [ ]:
distances_km = []
for row in final_single_city_data.itertuples(index=False):
   distances_km.append(
       haversine_distance(row.Latitude, row.Longitude,row.U_Lat,row.U_Long)
   )

In [ ]:
final_single_city_data['Distance'] = distances_km

In [ ]:
final_single_city_data

In [ ]:
f2 = final_single_city_data[final_single_city_data['Trip_id']=='NL01K8951_04092021']

In [ ]:
f2.Distance.min()

# trip  13 dec 2021

In [ ]:
df_trip = pd.read_excel("D:\\Sales Logistic Project\\trip.xltm")

In [ ]:
df_trip

In [ ]:
df_trip['Trip ID'] = df_trip['Trip ID'].str.replace('[.]', '')

In [ ]:
df_trip = df_trip[df_trip['RANK']==1]

In [ ]:
df_trip['Trip ID'].nunique()

In [ ]:
df_trip['Trip ID'].value_counts()

In [ ]:
df_trip.rename({'Trip ID': 'Trip_id'}, axis=1, inplace=True)

In [ ]:
df_trip.Trip_id.to_excel("Trip_id.xlsx")

In [ ]:
master_data.Trip_id.value_counts()

In [ ]:
trip_final = pd.merge(master_data, df_trip, how = 'inner', left_on = 'Trip_id', right_on = 'Trip ID')
print(trip_final.shape)

In [ ]:
what = pd.merge(master_data, df_trip, left_on = 'Trip_id', right_on = 'Trip ID',how="outer")
what.fillna('unknown', inplace=True)

In [ ]:
master_data.Trip_id.value_counts().to_excel("md.xlsx")

In [ ]:
master_data.Trip_id

In [ ]:
what

In [ ]:
trip_final.rename({'Dealer Lat': 'Dealer_Lat', 'Dealer Long': 'Dealer_Long','DEALER':'Dealer_code'}, axis=1, inplace=True)
trip_final

In [ ]:
trip_final.info()

In [ ]:
trip_final['Latitude'] = trip_final['Latitude'].astype(float)
trip_final['Longitude'] = trip_final['Longitude'].astype(float)

In [ ]:
distances_km = []
for row in trip_final.itertuples(index=False):
   distances_km.append(
       haversine_distance(row.Latitude, row.Longitude,row.Dealer_Lat,row.Dealer_Long)
   )

In [ ]:
trip_final['Distance'] = distances_km

In [ ]:
trip_final.Trip_id.value_counts()

## unloading-point

In [ ]:
unloading_dist= trip_final.groupby('Trip_id')['Distance'].min()

In [ ]:
unloading_dist

In [ ]:
# df['Status'] = np.where(df['Distance']!= df['Distance'].min(), 'In-transit', 'Unloading-Point')

In [ ]:
for i, row in trip_final.iterrows():
    ifor_val = something
    if <condition>:
        ifor_val = something_else
    df.set_value(i,'ifor',ifor_val)
    
    

for i, row in trip_final.iterrows():
    ifor_val = something
    if <condition>:
        ifor_val = something_else
    df.set_value(i,'ifor',ifor_val)

In [ ]:
for x in trip_final['Trip_id'].unique():
       trip_final['Stauss'] = np.where(trip_final['Distance']!= trip_final['Distance'].min(), 'In-transit', 'Unloading-Point')

In [ ]:
trip_final.Stauss.value_counts()

In [ ]:
f2 = trip_final[trip_final['Trip_id']=='NL01K8951_04092021']

In [ ]:
f2.Stauss.value_counts()

In [ ]:
#def unloading(df, fldname):
    #fld =['fldname']
    #res = df.fldname.min()
    #df['fld'] = np.where(df['fld']!= df['fld'].min(), 'In-transit', 'Unloading-Point')
    #return(df)

In [ ]:
distances_status = []
for row in trip_final.itertuples():
    
    distances_status.append(
    (row.Distance!= row.Distance.min(), 'In-transit', 'Unloading-Point')
   )

In [ ]:
for i in trip_final.Trip_id.iteritems():
    for d in trip_final['Distance'].items():
        if trip_final.Distance == trip_final.Distance.min():
            trip_final['status_su'] = 'Unloading_Point'
        else:
             trip_final['status_su'] = 'In-transit'

In [ ]:
trip_final.keys()

In [ ]:
 #df.loc[(df['ID'] == x) & (df['end_date'].isna()), 'end_date'] = tmp['end_date'].max()

In [ ]:
#for i in trip_final.Trip_id.iteritems():
    #trip_final['S1'] = np.where(trip_final['Distance']!= trip_final['Distance'].min(), 'In-transit', 'Unloading-Point')

In [ ]:
trip_final.keys()

In [ ]:
trip_final.columns = ['Trip_id','Lat_Lngt','Latitude','Longitude','GPS_dt_tm','Time_diff','TripID','Dealer_code','FileName','Dealer_Lat','Dealer_Long','Straight_Dist','RANK','Distance']

In [ ]:
#!pip install pandasql

In [ ]:
#from pandasql import sqldf

In [ ]:
#mysql = lambda q: sqldf(q, globals())
#stat = mysql("SELECT Trip_id,Latitude,Longitude,GPS_dt_tm,Time_diff,Dealer_code,FileName,Dealer_Lat,Dealer_Long,Straight_Dist,RANK,Distance, row_number() over(partition by Trip_id order by Distance ) AS ranks FROM trip_final ; ")

In [ ]:
#stat

In [ ]:
#trip_final['Status'] = ['Unloading-Point' if x ==trip_final.Distance.min() else 'In-transit' for x in trip_final['Distance']]

In [ ]:
for i in trip_final:
    id = trip_final[('Trip_id')]
        
    if (id == "Trip_id"):
        trip_final['Staus'] = np.where(trip_final['Distance']!= trip_final['Distance'].min(), 'In-transit', 'Unloading-Point')

In [ ]:
#for row in trip_final.itertuples():
    #print('in for:', row.EMAIL_ID)
    #if re.search(regex,row.EMAIL_ID):
        #ro_billing.at[row.Index, 'EMAIL_ID_val']= 'valid'
    #else:
        #ro_billing.at[row.Index, 'EMAIL_ID_val']= 'invalid'